kind: Secret
ansible_host: ENC[AES256_GCM,data:ERiMqRL1X7Tf6t/rzg==,iv:Dk+3uMVg3rotNFSDButYbL1Y0MLYaIogYDma3OWxrA8=,tag:SzZTT5K8G/wFDW8bn1UTsQ==,type:str]
ansible_user: ENC[AES256_GCM,data:Vg+ppQ==,iv:0fFtyRIqgQnFUzw+qQ3eivo/1Beq+ATDLuDLqfTXz8s=,tag:m811ax4oZzLcFifDkH6y6w==,type:str]
iperf3_client_hostname: ENC[AES256_GCM,data:wcqcXFqCpGMeeBzjKEdhBTVd,iv:6QbRWg/2DuZfzQf9iF3v2u7Kvk8yVhp38UfJAHuVpU8=,tag:QBTcI7tkwLey+SDyhbbtnA==,type:str]
traefik_base_domain: ENC[AES256_GCM,data:SVOq9f5q4YnjOOgPBr83XI12,iv:opfWJsuzKrz1RIrJy2LZlkv9kKbiDH+6mDM3/sCGUTg=,tag:K0mZ91EZxuJxwKSzzFtRAQ==,type:str]
acme_email: ENC[AES256_GCM,data:y8zLFFVrYgK1lhSgOjyloX+zI/El+PqmcU/ijt+QnA==,iv:WD0ut2jFReUf3XQf4CQwe9ZcWzvglFBz0s+W4jbFukA=,tag:8xxYgTTw5otZKLCrCxgp6A==,type:str]
amneziawg_interfaces_group:
    awg0:
        #ENC[AES256_GCM,data:8+fV9elj38VSg+DeMvsc,iv:QElQdlgog+UgAZRLlpgZwpWl6xa9Snc15O3r2EA+GcE=,tag:cCQNnnlEHGxWekVji2V1zw==,type:comment]
        mode: ENC[AES256_GCM,data:vjoEW8fW,iv:2A/ra0JL9EqyaNu9/szNFtdZIQbP8lz5ll1JR/5NCnQ=,tag:TxLQx22duarLTWmQHUE3zg==,type:str]
        public_key: ENC[AES256_GCM,data:K69Tbeo29NG3Pue+SlN1Hyk/W1GMMAk0Rg9AJdf52wm05VGi94rxLY6i+/M=,iv:QkNH+l05zqlVwgsZxRdzPilh43prqGidxc2s7GAzyt4=,tag:rIi/fvdmt3iFB1jyJ+QgRQ==,type:str]
        private_key: ENC[AES256_GCM,data:ks3kjuF9RRwAFYu6+R0vMbbTGfVfGgNScxhy/wg2pUwexuYFCknXOoYDrmA=,iv:uLyQQOzKmFFvCUfBDvSMHod7gSLKPWygEqjTd4rrql4=,tag:jyEanLAmdLLXd4t5P2vB/A==,type:str]
        mtu: ENC[AES256_GCM,data:5ZXOsg==,iv:t0ogDqzAnl+Yvpy3Q1mb4ipzyGWTLZpX8hZK3aLG4fI=,tag:BPbEW4DDKajY4BgrfcXnJA==,type:int]
        #ENC[AES256_GCM,data:4zEgxNuDRI5h5sBpsrkugeU5YbKlew==,iv:U5sxKGP4eatRrwMlpWYQNPVvF6MSb+COlY89Yl5hVZQ=,tag:cTOifZzKP8RlEre/E+cxKQ==,type:comment]
        address_v4: ENC[AES256_GCM,data:RmWyiR9NDp9k,iv:y8Nt/X9q3EzDBWUP/lRB0HSCAblEmMHj3soFQfG1AmI=,tag:rlwqpUN8T6n8yX9vKiUZug==,type:str]
        subnet_v4: ENC[AES256_GCM,data:Z1w=,iv:Q/qMb3SYzodNpxYGtOrnmIOIe4YC4E9GOMk16ddmcbs=,tag:Au95v6oOrqGmxKDFhDB+Gg==,type:int]
        clients_subnet_v4: ENC[AES256_GCM,data:s7g=,iv:gdfb4+S9h9mwxjYICaBYZ8kZ9wU6GmtnEwTBpLz8SHE=,tag:8oard6+i9R5ju3lTuAAvWg==,type:int]
        address_v6: ENC[AES256_GCM,data:uET88FTaCFk4nZtrJaDD0x8=,iv:vMLj5AS7NuBmpYG7Xui+uPjwdxZKt31HiRLp+8Vc0uA=,tag:60vY1MH1AYpprXvkhBhcCA==,type:str]
        subnet_v6: ENC[AES256_GCM,data:2C0=,iv:u7undugUVhXsbBshcg0C63WNVQ8ODpLHPXSp6zFgUkE=,tag:Jjme84vQw8zs12EixDPWRA==,type:int]
        clients_subnet_v6: ENC[AES256_GCM,data:ikRo,iv:ADXn5T/cNynQU5r9/5KieCQiccVqhCzCyJNQJwYtbBQ=,tag:/PH2/zYuoCld3u6XIRd/KQ==,type:int]
        #ENC[AES256_GCM,data:VQzp+xdAV9NG5zqzUbq77QyFsbPK,iv:xe7bSmZfvKfYfocwz2ytnABoBfFIIhl05yeIu+2XoTI=,tag:Gq2+cjG5QyM7JgZ5cVe9ww==,type:comment]
        port: ENC[AES256_GCM,data:HtceGJc=,iv:VXA0fNjVaydHcVIk3dc1rKe3uSqzJlBU23pcHEdnUa0=,tag:dE9WBsbixMTmMNyWS0iYag==,type:int]
        public_host: ENC[AES256_GCM,data:V08xgukdQbdv1U2g6iU8NkFk,iv:WZ6X/7B5F7gntvvsb8SRXzZQOeDY2VihKc1ri5h2SUc=,tag:PaLB5gPAqLMxI/kP6RPm6Q==,type:str]
        #ENC[AES256_GCM,data:WrciB9S9MNG18PgD3jghEEd3cgZkHEQ=,iv:OGB9KYFwqcpFPlJBTAPQEXUsxOP9vyK6++UeOsUhuv8=,tag:RJ34dBxQg5nfplyzqO7rqg==,type:comment]
        private_interface: ENC[AES256_GCM,data:kh3gOw==,iv:rORuyvGplZRKERQZCpERXh5vt+AZmiJQPYatdiyUMdg=,tag:jPo5xxPwVAZeJFLKpypJVA==,type:str]
        #ENC[AES256_GCM,data:6Vrh5NhlFDV081MR+FVIlak2BeUjJa+FuTQ=,iv:kj8H56J1xS3p9JvbFKg5bmkUcHVwx9lUcAeonar75Wk=,tag:qEEpjdyV0a9dn3c54lcjPw==,type:comment]
        #ENC[AES256_GCM,data:8/Y2bwYbb78xcw5BstSlElhzBeoc/TGBICQf/uJ54G3pQ/66YbRDFjWdtaqnfVPuYLwf,iv:LfC0hx41EcpjGNrm18g8sjb4ivn4UN/3/xW4gQUstNs=,tag:/Dxh+QTGnVKnVTNjpQ/ycQ==,type:comment]
        jc: ENC[AES256_GCM,data:dA==,iv:MnkSGVslvrXFoP0NmTQJs0z1TytugcbHw3PUEYlJqoA=,tag:bTjNjo5EApB9cKtoMhKNgQ==,type:int]
        jmin: ENC[AES256_GCM,data:4fTo,iv:w0+YW6vhTh7RA6i/qeajNEkIgj/O2G0j9f+2CuItveA=,tag:5LJhtoZjPygt7726ek7opA==,type:int]
        jmax: ENC[AES256_GCM,data:RauJ1A==,iv:UO/H9Ouuq4xCaYcPDz7Thne9uiGo73Z9L33KD8XF/o4=,tag:Si2C1l5E6duVWcTCDtkNvw==,type:int]
        s1: ENC[AES256_GCM,data:xFA=,iv:xSL/INth7mzDK6OjpV7h8yn2EZdcC2gqnN6ONeMoww4=,tag:kZNLw5XQdvo7ZCPH85q/5Q==,type:int]
        s2: ENC[AES256_GCM,data:EFs=,iv:i5dE9DHgFJTZhi0vVcRQo0MSl8m/fX2EOwAecTLl3LA=,tag:AkuNgM8WYVyA4xp/z/CEQw==,type:int]
        h1: ENC[AES256_GCM,data:5b4kzZy1oqDe,iv:L/7xzeLlmP4KmgmC4SC+wul88dplYu7A13k3wV3s3ic=,tag:PRiyikP7mXA09lWqyf7elQ==,type:int]
        h2: ENC[AES256_GCM,data:vFd7i9ce6HUr,iv:OTgvFTov0oNtXhkDuQmc8yGSuXxEKs8uX4iHSqrjWNU=,tag:c5FrxrzQ4+9T/I2ylB7AtA==,type:int]
        h3: ENC[AES256_GCM,data:ZTqjQM2ZjFBGbA==,iv:rwCNlU7FDnPhmd6Tm5KnCwE3vKZtG0tTBijwim0UioU=,tag:Z4Q3N8ovh11KsRjYa1PNbQ==,type:int]
        h4: ENC[AES256_GCM,data:zur3bSp0TFLX,iv:CXvG3C70URh5hIAo2YXFoM3pZrA0GOr2q2c1nVDXJZA=,tag:BzVr6+1a5V0yZs4NanB6cw==,type:int]
        peers:
            - ENC[AES256_GCM,data:cM4jIWynylui/gqq1A==,iv:U8McG3Kj54aJ6EqxPdRJl0zajv2TV25Kwe5p9KCOzk0=,tag:TcAbYJsw43Zcod0BaTQKtA==,type:str]
            - ENC[AES256_GCM,data:FtYWzjoW,iv:KX5j2EufG/h+9xrk6SNQXKNiafxpnp649cpVui6aNEM=,tag:eDxVXJLsiSKDJhG2JLr9PQ==,type:str]
            - ENC[AES256_GCM,data:8J3/NgpGdgZp,iv:7ByZDCzWRD81VfEcEOnGiVgIv8tFGfRe8ZBoX8PxOdM=,tag:fKb/usXof6F/Qv0bnNS3Pw==,type:str]
            - ENC[AES256_GCM,data:iHaC18MpxVJ2Wdul,iv:dOC9y868I9KHBVVCkpai6I4N/5eslxCsIqrh4Vu80IA=,tag:wvw7TgwpoWoGtlRDlgn7mA==,type:str]
            - ENC[AES256_GCM,data:eEbYgZMFXWMBIQ==,iv:y7GUuY+0psCHoPj4whBkipNjVvusAti8252z9g2GzRU=,tag:ctzUNQuem2jNs5YktpsOgQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTTJ0bmFacVJLTFkrZ05n
            OW1JRll3WlZLT0YwNE4zMzN2cUc4bnZtTURzClNudHpTWnRER2x3ZW0xSWpNTGdr
            WDcvS2ZxWjZ2TnpTd3Jhbkt5cEtPeW8KLS0tIHhTRG9QQ09yL2pCd1hmVjh3TXl6
            RllMSitwZzFVSi9QQWh2RCtncTRCL2sKCFxMUdbDQXfQROJJSyvixrr+0fT2sHDQ
            nItkATY2pidSwBmpIBPt64brx+0lPCKFg7phdO1DiRUZ12l8a+BOGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
    lastmodified: "2026-08-18T19:16:20Z"
    mac: ENC[AES256_GCM,data:4lt9fX7oeD+Ehibe06lDCJ8rbDA2Zojq5QKvMwbg7gpY9x8cXwdvbeeYuMvSDmuNoxwnjvJwLCdaCLZXF2kqPueMU9M3NGOE8wl7aqal6ZG/0bSv3Q/5NVB3t7LqVLDGi0eiTnNoZ7JlU7tJGbVvetmbCLxpsoVH/Wj8Rhk4KG0=,iv:o1zVCmemIvOpWdVPENPBh5/IyA+2l2SZu5juxAuJ+UU=,tag:bL+WK01WRk4CS3Sa3yFdzg==,type:str]
    unencrypted_regex: ^(kind)$
    version: 3.13.3
