---
collections:
  - name: community.general
    version: 13.1.0
  - name: community.sops
    version: 2.3.0
  - name: ansible.posix
    version: 2.2.1
roles:
  - src: xanmanning.k3s
    version: v3.6.4
  - src: mrlesmithjr.netplan
    version: v0.4.3
