---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - echo-server
  - external-dns
  - ./k8s-gateway/ks.yaml
  - speedtest
  - ./traefik/ks.yaml
  - ./traefik/authelia-chains.yaml
