#!/usr/bin/env bash
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(git rev-parse --show-toplevel)"

exec "$ROOT/scripts/pre-commit" exec hook-impl \
  --config=.pre-commit-config.yaml \
  --hook-type=pre-commit \
  --hook-dir "$HERE" \
  -- "$@"
