apiVersion: v1
kind: Secret
metadata:
    name: keen-pbr-metrics-auth
    namespace: monitoring
type: Opaque
stringData:
    password_55_1: ENC[AES256_GCM,data:yn+i7dGVAlBA,iv:hMoDTYanc+E8k32QEpFDGbbq0NiTgNoLCPuw3+rHwSY=,tag:nRZlTXfZzonm/j1BunNyHg==,type:str]
    username_55_1: ENC[AES256_GCM,data:VYMHDbc=,iv:UeOBMXQxa/P36yVCzAT/Np4pNUEw1BZOmyQMYP5eRxc=,tag:/ELeVFirWdxQR47IcOnRVQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dCtkclNYTWNITUdrN2ZH
            RGQyWjF1U1d0Q0NDVlVFSUZGdzZiVjFiNFZBCklGNzc4d050akE0b1NrdGVTWUV1
            MGU4UXFnZEV3bjdaZkxoajlqNXdRYmMKLS0tIEE2TkJhRmt0Z2ZCUFcyaHpWMXc5
            VzZUcnpRL0hmajBWbzFzQU8rZi84bGsKoUaKAVi+vMLgn5aqMtbfga5nM7dIQSb0
            heqvOuXNLBAozFWpCBILt2WHQZ120zT10BcBdB8YD62NBGzHz+etpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-10-07T22:09:01Z"
    mac: ENC[AES256_GCM,data:QjnVxGZXA8DzUVBxRK52j259aRwEnRBu5zJlMMKWjoNpOlVlvy+2Wg5/NT+ChC+VYkFEEGgls/685HxmjnYvGkf4wbrU6v45w35y7HwHrUQXM8dUDdfdeiLzHJdinv9eEg6/dnw8lcjw89i2BkuUGi3Fq08p71KedXw/zONuBns=,iv:oEJNAqncybFhdTC1OL4h3ephsCC1RvhwKMj8Zvxn0SY=,tag:9bqDv8HzgDzlz2bwBfA3Xg==,type:str]
    version: 3.13.3
