# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: orthanc-env
  namespace: default
stringData:
  ORTHANC__REGISTERED_USERS__admin: ENC[AES256_GCM,data:3iUQTlOx4i5wDyOWSQDqO2APcIrs07BPE8b7Ow==,iv:5D8JG/VTvOfOOuedIyfX54ChX2iEYBrxwZgX+9xKx9w=,tag:1RlKFSCWl6wEE0LcS6vIMw==,type:str]
sops:
  age:
    - recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbUZqaWR5RGx1NFBKTmEx
        KzB4MkpwdkkybHhtQm5jNUpQNC9nMFRHQVZzCkRXd25lQUowL3Flc2gvdWxvWFo2
        UC93d28yRWttT3pUb2wzNkJ0V1hRM1EKLS0tIG1nZlA1OU5EVCtucnVCY2pTTG01
        R25aSzRqM1pxZkthaXNuR3JoRHVmL1UKhNK62mhKPHWv50m+wzLYoDG+TlvGYKUN
        BZuoJePM/nurCnNEooBai1yCiS16GvobNIyziiTy7gYm6TRN2srcIw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-13T17:10:39Z"
  mac: ENC[AES256_GCM,data:K00Sl3AfqjfrOBxhs41JdSENMO9w610szOx85+7USR3f+kB1Arf543egnzdietqe56vqEIlc3k6easxpYnAj1ZeizbtdEZBVupsiguUiXOTnbUwbhFNopgYkPEQtp2LUT8EC6bGVPpK8q1J7hnVm4mbZrvV+NT2OiR49ToUhOI4=,iv:Bk06p2xyceGxhHQFnphr3/0ZeTl1uwvgZuQcL/SMqrI=,tag:XCJ80UGCvvqXAzND1lIorw==,type:str]
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
  version: 3.11.0
