---
- import_tasks: 3x-ui-install.yaml
  tags:
    - 3x-ui
  when: vpn_xui_enabled | default(false)

- import_tasks: tgproxy-install.yaml
  tags:
    - tgproxy
  when: vpn_tgproxy_enabled | default(false)

- import_tasks: mtproto-proxy-install.yaml
  tags:
    - mtproto-proxy
    - tgproxy-mtproto
  when: vpn_tgproxy_mtproto_enabled | default(false)
