# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ${APP}-secret
  namespace: ml
stringData:
  BETTER_AUTH_SECRET: ENC[AES256_GCM,data:X8e9HUhmMxF1Qi9mdRVIlIIdxsNQ/8sTvluEr57eTjtmLnIJn86LrIHFGZ9jc419,iv:vhvvovaOCNDvAgrC8kD5hmPirhpAnGnN/P+x4EKc/0M=,tag:axSU8RxchfL458mSx8eaUA==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:OXyrDGoYCjyJDuksr0FBikgbsQQXOqXTkn+CJQMGkXs6JN1ZJvmUkWf7VMaN34oP,iv:/HENVWlciXZyIUUPZ5NZLZP8EECoD23rcUwxu2g1L6g=,tag:Tx8b9VaB9Zxbfs7biHJz8A==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:Bsg87rBvTMM1PmQTUEBoQrZzzTuP41GUh2FJEcx21xDpHagTttpSs5PKlA5HL48bcDtz4j8kJcCaBK5Vy9/wHQ==,iv:jSU2AWXzLeICn+DLzfUBROLHGPhjM40lRUmgcEmJHjw=,tag:7dTViCDljMRVgx7Nv49P1A==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:B2qeGXTHjAsazzldeWDYhYfWRfvM/Lv7LgAKS7Z0Qg9gRNq5PcH9Mg2ON7H44EQXwYRKRGY35Wm9FQ/PiXIQOqpLJYJ3hsxdMASlXycKYeNvc/uZmJI0H8CXeGRMcw7y/UICkCI2fbUpH1hiH8xBx2hIthnQzibDoQ==,iv:pSeX2zHMIWurmeJBxw5tuXiqtd0Hn6MjkLTDKn6Qpd4=,tag:6ABmacAgfuqfRFY/KA8uHA==,type:str]
sops:
  age:
    - recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVXIyN3JvV1dsY2x1dTdF
        T1dBZzBTQXk3OXRQbHkwYTYzSiticDgxRmlRCmdTYnpEL2JWMEpqQ3RLOTQ3TWtF
        dzJ3LzNzckptU1FjTjNlSXBBQW44d1EKLS0tIHMzZnk4NkwyRnN4cUlOWDdBYmcx
        dnJIcE1oK0R0enlCMzhwczY0S3JYTWcKspDczcLRPHJL+KNv8yJS5iUuDbAGINQY
        pJSt3x3sDDbCsYyin+8OoxspA4sMXoqtzxRz2+sPDUwslixI30rTdw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-30T16:27:48Z"
  mac: ENC[AES256_GCM,data:dubued/OuaW0G6FpIKN4gC5lX20QjwpemWoiKu7KenxYFAptUKLpsqp/sbTYg5tGUpe0QulvWnRmpBU9t+8UQpLx5PQBEpblXkUhAyN+WHOgKy0Nz/p2aZmUnVnEZ+fgMiW2LbQ2AeIjwxiIfesrRccDVZTwlYQVzvQP1vVGL3Y=,iv:1uYTYrsW0H3xbZvNYOPE6RofX4XCC/a9mz9EZc1pWZs=,tag:NVxzy7gWDqQdE5jLJkya6A==,type:str]
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
  version: 3.11.0
