# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ${APP}-secret
  namespace: ml
stringData:
  BETTER_AUTH_SECRET: ENC[AES256_GCM,data:+gg9s0ccqM1+FGQM66RIqLwGgDPzxQuf4sVw5PKKcOjDXebCno6fUq/VLUVG9dJ5,iv:Fou+CRyNlNcNeEOBL84DUhbtDfQzwB6nc/eGTXe1URo=,tag:KlXiIk/fq+gvGvvrrS8n9w==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:CXZJNmXEfoP6VDIf2xNywyiHrfVRMKQZBThZ4TYfi4Twi1/DQDcRqIsHrk2FHwPVbO9WOhOxGy1L4WX3Bcb9dA==,iv:cvkm7PFTJnFakJjWqW+HIO7IhFDy+truP3n4VP0jO7c=,tag:p/Uo0XDHsf47hmD31geF4w==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:pleDI+mzicaoO+4n+XKIO/esvgqU5h/7GMWZNs5KdjszBrp6r7Afkpd2ar0m7pZr9s6252zeDHsGVHhopDGZFy3r+QgKzAaIF9Yajja4Mb0KH5pWTrMf4vZz4LTYJWPpMI0Ey02ZWLQ78U8xVzqZfSu/LdiANMmy4V4mcYr7c1T6CgCLQukuFkI=,iv:T+5uSK0TM5z84wT/XsJ/IGzSWeeztJcfxVzJvYYUIqY=,tag:p6HFAR+TfAGxpwVC76uZHA==,type:str]
sops:
  age:
    - recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUTVoQ1hwZDNSaWJFU0Vu
        UjA4YTd1QkNRbjE3RStyMTd4Vkl2Zy8vV3hNClovdXcreGJWb0IzSEVmWTFZOUl0
        Slg3STRvK2dmNnFFOFNLV0cyVE80LzgKLS0tIHNhTnVWTUFHc1FkQWdrOWw0Tjl6
        eWtlcGcvNFlnOW9CV2VYdFFyUTd1WU0KQw3QT2PEjGjDr7xRoNpVVxNmzjBDqqoc
        ShhgGUZlRtg3Lmp8Gn1beTbpyeh6/mHnlGumyoEcX6S65Kw1rXlqTw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-30T16:04:35Z"
  mac: ENC[AES256_GCM,data:m3laNb18/ZRdi8XGTlvRwXoXSkY0Aba73wUuWU6zDpojKvO4Gk3xGvcTSFD+zg5iBNVH3APraJM2nGocLrv/ikmqtt9jBJceic3TTPW2OgyWOvXKifHBMk6Qzc4b49gO6XuLeCzN5KMem4N0JQRE3IPyA4MEBcD1SPcn9YgUGks=,iv:Z5Tqw2RDzzqLV30iCpvrx+ZjxG77U4naDzPMtdK12os=,tag:jBtns30zYRSwrUT9xS68NA==,type:str]
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
  version: 3.11.0
