---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-5.1.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app capacitor
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 5.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      automountServiceAccountToken: true
    controllers:
      capacitor:
        strategy: RollingUpdate
        serviceAccount:
          name: capacitor
          namespace: flux-system
        containers:
          app:
            image:
              repository: ghcr.io/gimlet-io/capacitor
              tag: v0.4.8@sha256:c999a42cccc523b91086547f890466d09be4755bf05a52763b0d14594bf60782
            resources:
              requests:
                memory: 1Gi
                ephemeral-storage: 128Mi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: [ALL]}
    serviceAccount:
      capacitor: {}
    service:
      app:
        controller: *app
        ports:
          http:
            enabled: true
            port: 9000
    route:
      app:
        enabled: true
        kind: HTTPRoute
        parentRefs:
          - name: private
            sectionName: websecure-private
            namespace: networking
        hostnames:
          - capacitor.${SECRET_PRIVATE_DOMAIN}
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - identifier: app
                port: 9000
            filters:
              - type: ExtensionRef
                extensionRef:
                  group: traefik.io
                  kind: Middleware
                  name: oidc-admins
        annotations:
          gethomepage.dev/enabled: 'true'
          gethomepage.dev/group: Maintenance
          gethomepage.dev/icon: mdi-cog-sync-outline
          gethomepage.dev/name: Capacitor
    rbac:
      roles:
        capacitor:
          type: ClusterRole
          rules:
            - apiGroups: [networking.k8s.io, apps, '']
              resources: [pods, pods/log, ingresses, deployments, services, secrets, events, configmaps]
              verbs: [get, watch, list]
            - apiGroups: [source.toolkit.fluxcd.io, kustomize.toolkit.fluxcd.io, helm.toolkit.fluxcd.io, infra.contrib.fluxcd.io]
              resources: [gitrepositories, ocirepositories, buckets, helmrepositories, helmcharts, kustomizations, helmreleases, terraforms]
              verbs: [get, watch, list, patch]
      bindings:
        capacitor:
          type: ClusterRoleBinding
          roleRef:
            identifier: capacitor
          subjects:
            - kind: ServiceAccount
              name: capacitor
              namespace: flux-system
