---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  # - generic-rules
  - ./gatus/ks.yaml
  - ./grafana/ks.yaml
  - ./scrutiny/ks.yaml
  - ./victoria-metrics-k8s-stack/ks.yaml
