---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  storageClassName: minio
  persistentVolumeReclaimPolicy: Retain
  local:
    path: ${NFS_PROXMOX_MINIO_DATA}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
  namespace: files
spec:
  volumeName: minio
  accessModes:
    - ReadWriteMany
  storageClassName: minio
  resources:
    requests:
      storage: 1Mi
