apiVersion: v1
kind: Secret
metadata:
    name: ${APP}
type: Opaque
stringData:
    SECRET_STIRLING_PDF_ADMIN_PASSWORD: ENC[AES256_GCM,data:ixccls7CJW6pApY7S14qS+SfucpB97qkttgEklkt5syzOkEo+4uyAjgQD3GyYvCx2PE=,iv:97/GPQ7wDtrZ/p2/C7WsztuHSGEEyIfRyiQFRN/kugg=,tag:tgzjV+w6TK60u/kdcwY35g==,type:str]
    SECRET_STIRLING_PDF_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:sJecIEJgEPfVn/FNw6x3/BPRZ0EHcAhfVs0rTWXdosA=,iv:/eMlWsVUWz3glN49NjMBKM5uWeBtoSfjjxyzZkdxSiY=,tag:Vbgs8EqLF/YJTwepxXzKTQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNUFuMGg4TzlZM1FDU2Vh
            M2JONm1ncU54YWVnUGNlSXc0ejJpdUFtU1NzClArcSswRXFNQlhpRXg3cXJza2p5
            YlZRYXRmNXl3N1NrbjdsQWo0ZFlwWkkKLS0tIHU3ZEg1eHpKczZ5b0NZQ0srSmN3
            VUM3elFJR2ZVWWRzTDVaNFR1QnlvckEKM58nTTFzFw1qgXqyTz9XLOScCtCwK6Gy
            24va+EJWmZeJb6QlnXzgy9ZlJZglxeDA0RT+Yp6bJoV4Dk3M+HBcmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-28T17:33:16Z"
    mac: ENC[AES256_GCM,data:D30PqcHulp0UM85d+AtHhV0rNC6/iRg3GxtRhZYQaScUh1U70lQWusZxOpMA4zHbPTh1FhE4Pp+sn6vdvX4OHwFyRqedKI7UKIkr8b2JA50uxMfK6/DslntnTzc2pqIUEK19Bid+8nRFrctRjJSZJ9refTfdJf5AFtrPvXpe7DY=,iv:HmAJU2XLlNOGDaYj2TwudK8gvqVHRSuElGLQMHkevAw=,tag:/IXcazoNCndtgZck3bDZng==,type:str]
    version: 3.13.3
