---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.6.2/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${APP}
  namespace: ml
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s-labs.github.io/helm-charts/
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:

    service:
      app:
        controller: app
        type: ClusterIP
        ports:
          wyoming:
            port: 10300
            protocol: TCP

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: local-path
        retain: true
        globalMounts:
          - path: /config

    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: feature.node.kubernetes.io/custom-nvidia-gpu
                    operator: In
                    values:
                      - "true"
      runtimeClassName: nvidia

    controllers:
      app:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: lscr.io/linuxserver/faster-whisper
              tag: 3.1.0-gpu-legacy
            env:
              TZ: "${TIMEZONE}"
              WHISPER_LANG: "ru"
              WHISPER_MODEL: "base"
              NVIDIA_VISIBLE_DEVICES: all
              NVIDIA_DRIVER_CAPABILITIES: all
            probes:
              readiness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 10300
                  initialDelaySeconds: 10
                  periodSeconds: 5
                  timeoutSeconds: 1
                  failureThreshold: 3
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
                nvidia.com/gpu: "1"
              limits:
                cpu: 2000m
                memory: 8Gi
                nvidia.com/gpu: "1"
