# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: frigate-secret
    namespace: home
stringData:
    FRIGATE_MQTT_USERNAME: ENC[AES256_GCM,data:GbQJTygCrw==,iv:AvkO/e4jEQ2yqm6ORewv65JletvPH/03/OWy4OitJgI=,tag:8hiv2TH+ajwEcxW0aAo0kQ==,type:str]
    FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:jVt1ZoTnDn2G8wEWzg7ub2h0xgofGMLi,iv:bvcBdRFxgzgxgGJwfhfpueP2qqi8ohVv6QNZloOkjp8=,tag:GRxZBOrVp/GeeCZTdXUbJA==,type:str]
    FRIGATE_CAMERA_HALLWAY_HQ_RTSP_URL: ENC[AES256_GCM,data:wYgI0Xi7MUxL/F+otS9VQzugQvUsxQ/W9D8icYGEckVjwYE0WFcZ8rL0N6GqFzaOrf/wL5H4X/bzGACF2mmx+YQcjhxh3aTXvYXYmL9cXK6NiWuxxa4eZpcazZfA,iv:v4bmh4JnTMBXyKvcLhjvHvclj0+dePM7QXEPL7WOuI8=,tag:O3fAJcbL0owp1T11WXfj7A==,type:str]
    FRIGATE_CAMERA_ENTRANCE_HQ_RTSP_URL: ENC[AES256_GCM,data:z3R/bENz3wJKCYyYJjhax7g6lR96XFI06QBFPtihRFtBGKGcXIu7ACAvXWJzvNZ4CH3H8oeluspLOgv2vl8a7IfMosyCToOUYuGY33rxVxF28ZLdcFAnrMRxIG8u,iv:9ol4dQPzpH6G2pDlqBlgkOe1KqNBlTj6JUU9Qab+eL4=,tag:IAD7Y0hdwodbhLDsWVipVg==,type:str]
    FRIGATE_CAMERA_HALLWAY_ONVIF_IP: ENC[AES256_GCM,data:4TnO6WtMUJPFqlqCKyQ=,iv:2PWCL4x4hxZI3A+7RcUFOZ8wv3AO1+NiQ1Auv5PsTOg=,tag:oI10oGXjnkWFLNsMJHJOoQ==,type:str]
    FRIGATE_CAMERA_HALLWAY_ONVIF_PASSWORD: ENC[AES256_GCM,data:3PPDj5NvDyHapjk2G33LT/Z5HRYvtQ==,iv:R/RpTRX2tTrNTJEtwE78dYTKcPTEvdkoHVDRFejO69A=,tag:pvdpufs/kevrp8AnaFrgyw==,type:str]
    FRIGATE_CAMERA_HALLWAY_ONVIF_USERNAME: ENC[AES256_GCM,data:cBzA990z8Q==,iv:WVEy3EVTLJhCUzILQVAuQC5oCKddEj0hcqWmUR9rEPM=,tag:vMNxS/n9+SUQuwdj58mPXA==,type:str]
    FRIGATE_CAMERA_KHOROSHKINA_HOUSE_CCTV1_RTSP_URL: ENC[AES256_GCM,data:00LGF462hjW82nB+8K0o5IGFGEXAsq/ewl0kf+6FTVWfce93oIxGTEGYFQ==,iv:ZU5oML1P2Fs9TwMbBlP/iwLPrrlV1PBADPF9yA9L+5w=,tag:3njt3DJ07Xl5VFQBQY1COQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZ0J5VjR1MllXNExtUnJx
            N2xGekxwR1g4MmxoUStMZzZuZ0tOYUNySUhJCitkQ0xBZkRXcm5pVEY4bUZWN2Zo
            ZUM2bzljc2p3RzV0SCtSNUFPRVl3TW8KLS0tIFhRNS84N3dWMFcwWnI2ejlpYlpi
            Y1JrM3dzOUZBdm5UNUg2ZURrQ3UzOVUKC4OQu8vdHbSOkisYPcN9lZYPs1TO3w7Y
            UysTCx/kfItjbE4gOJVJQ8oG82WBtR4/VxSNdNvS9qDKwiIzHxaJHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T19:48:57Z"
    mac: ENC[AES256_GCM,data:44D9LX2zjbxA6bCKECFrHr0qitl+8IRWHtsDCBAd5dSKPE4O19MQGnmm4tkiDBeXtYmY+g04HGmywA5FRDa5bX6mT6ydoDaVWU7zzTea4UfwHmBzYAW0wfvTSRyA+oRsuAsMbjsWltRzuKbaHCMqnsMpP7NYY/qcaTxeNGxoDys=,iv:m5PT/4uZaVMKeVnF6HaKkg99LXgzVw6Q9iTQMs5S200=,tag:YbppXBzc7zYj9PJsAiOLoA==,type:str]
    version: 3.13.2
