# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: frigate-secret
    namespace: home
stringData:
    FRIGATE_MQTT_USERNAME: ENC[AES256_GCM,data:GbQJTygCrw==,iv:AvkO/e4jEQ2yqm6ORewv65JletvPH/03/OWy4OitJgI=,tag:8hiv2TH+ajwEcxW0aAo0kQ==,type:str]
    FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:jVt1ZoTnDn2G8wEWzg7ub2h0xgofGMLi,iv:bvcBdRFxgzgxgGJwfhfpueP2qqi8ohVv6QNZloOkjp8=,tag:GRxZBOrVp/GeeCZTdXUbJA==,type:str]
    CAMERA_HALLWAY_HQ_RTSP_URL: ENC[AES256_GCM,data:dIO7f2b1yD1jnwXU7dYX0x7U0sySbDdty7MURufzDp6Rd38O3oF5lYjbYu2uX0IcbI/KI0lIiJskt1hgQm0ebB+5mb/jvIbU1ZPmqduzEAFURuiVT+pwEGr/RycQ,iv:UfGP5Xwt/zpgmhZW/SBRtaAVlp3/ZmPQmheprkIIeSI=,tag:uhkt3IcU0MvWMFdmsqZPDw==,type:str]
    CAMERA_ENTRANCE_HQ_RTSP_URL: ENC[AES256_GCM,data:n/wnZkXEA71o0JuuXL3itaJUxOnoYAjvcTkLzvBgF3/scRww/qWHOt6N6/icSTsX2oEqeGGoY67c67SkoaI8KBnhSnkHXH8XMrAv6ndNQlbeQDswvYP6HGd0K6ds,iv:WI5ibF7lXq6XhAWi1mKEDWZr4R4Ph+S9HQl2LHnd+V0=,tag:JSPc3+uRkOZ/cE54AY3f6Q==,type:str]
    CAMERA_KHOROSHKINA_HOUSE_CCTV1_RTSP_URL: ENC[AES256_GCM,data:RuYFKMMqMi55p00ozPXsrrYwi2djqfEhZIvyyzAbiM7g7VZbWkiP4Nu+QA==,iv:7vlM1mJCEjrSL77bUvYDBEvXtAwRSC5ZAzG0ku5aslA=,tag:FJ+LEv1poLlHX/H5WAuyeQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZ0J5VjR1MllXNExtUnJx
            N2xGekxwR1g4MmxoUStMZzZuZ0tOYUNySUhJCitkQ0xBZkRXcm5pVEY4bUZWN2Zo
            ZUM2bzljc2p3RzV0SCtSNUFPRVl3TW8KLS0tIFhRNS84N3dWMFcwWnI2ejlpYlpi
            Y1JrM3dzOUZBdm5UNUg2ZURrQ3UzOVUKC4OQu8vdHbSOkisYPcN9lZYPs1TO3w7Y
            UysTCx/kfItjbE4gOJVJQ8oG82WBtR4/VxSNdNvS9qDKwiIzHxaJHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-01T08:13:34Z"
    mac: ENC[AES256_GCM,data:EAhUU8Pu8rwyocwqeETRtzM8EnvoRLcBIuBOd6dYU6wY/uxL5x4zAtFRdXYeV9SToX0IIrylKCRPo9Smb3mCAFbczrylpLnCj1OYOhtTUl+VBYZDNSLL1Hi008XUQigG/JjboJYyxxET5Ok7Hb2gXDnUXEDm3ehJbB5DdeBzOzs=,iv:1gFeNVKRCJekKsqMLExrcZ8t+vwFmUtqwMVwHn7pqUs=,tag:zUeTUlnAR9uCH9m6Dc7ezA==,type:str]
    version: 3.13.1
