---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-5.1.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${APP}
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 5.1.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: docker.io/chrislusf/seaweedfs
              tag: '4.29'
            args: [mini, -dir=/data]
            env:
              AWS_ACCESS_KEY_ID:
                valueFrom:
                  secretKeyRef:
                    name: seaweed
                    key: AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY:
                valueFrom:
                  secretKeyRef:
                    name: seaweed
                    key: AWS_SECRET_ACCESS_KEY
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 1Gi
    service:
      main:
        controller: main
        ports:
          s3:
            port: 8333
          admin:
            port: 23646
    route:
      s3:
        enabled: true
        kind: HTTPRoute
        parentRefs:
          - name: public
            sectionName: websecure-public
            namespace: networking
        hostnames:
          - s6.${SECRET_PUBLIC_DOMAIN}
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - identifier: main
                port: 8333
        annotations: &annotations
          external-dns.kubernetes.io/enabled: 'true'
          external-dns.kubernetes.io/target: ${INGRESS_DEFAULT}
          external-dns.kubernetes.io/cloudflare-proxied: ${quote}${INGRESS_DEFAULT_CF_PROXY}${quote}
      admin:
        enabled: true
        kind: HTTPRoute
        parentRefs:
          - name: public
            sectionName: websecure-public
            namespace: networking
        hostnames:
          - seaweed.${SECRET_PUBLIC_DOMAIN}
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - identifier: main
                port: 23646
            filters:
              - type: ExtensionRef
                extensionRef:
                  group: traefik.io
                  kind: Middleware
                  name: oidc-admins
        annotations:
          !!merge <<: *annotations
          gethomepage.dev/enabled: 'true'
          gethomepage.dev/group: Tools
          gethomepage.dev/icon: seaweedfs
          gethomepage.dev/name: SeaweedFS
    persistence:
      data:
        storageClass: local-path
        accessMode: ReadWriteOnce
        size: 50Gi
        globalMounts:
          - path: /data
