apiVersion: v1
kind: Secret
metadata:
  name: seaweed
  namespace: files
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:5i9ve52Z0cL3IUcxWBYwPbhW,iv:AR6Jq/9bGRe17jHOFg8GDx15ClaKvzZOJcVsOSReABo=,tag:e1fq6FxYnkCvU2n3auF7/w==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:xjXXMf86wdhZKJ4GlMMUtXyosLv3DJtRzTHv5nF+3quVKnKpJBQdp9G0Q1Gao7rHrEVgbhPv2YY=,iv:QyNQJPHIvACDRHPhxHhYM7HvyxmchG9jDtyIJZ0rNDs=,tag:iQdFqnUT9NE4uSAlv0DNNg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlcERzU1Z0YWdlRkRtRjkr
        bTBKclo3dVNkRDBSYnNhazh6Q3lQUkJ0eXpzCnFXa2M0MVZ4bldua0psKytGUjNR
        Wlo4NTZESXAyeUczR2h2WjRSdXdjaFkKLS0tIGw2NzM0VU1qd25vV1RSWjRqQjli
        dlo0eWxvNHNIamhlMlh3bnhXM1VSaTgKb91+MAIeQGISfyPju6dZpLdfk4LSZpLd
        NZljk5oBxqh+npExOSJnZzKbTL9A0TTBXKtR+BEE7hmMY+25MiN3tg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
  lastmodified: "2026-09-17T07:46:57Z"
  mac: ENC[AES256_GCM,data:JFns3w0hTO/TceM24n2LGUoj22Lw3BpkyS9lNoSMwKtGbaSVpNnFmGh9U//869wzRRnHe58E1O9pD7jHvCXCJ2oNbyVfYcfkzUIDhI7NJvs6+Q+gtG1/tbjuVfMPaz26yiJ/7J4T2s2DngQSgJ29lUKyNc7qddJuGyZHFhI+Rd8=,iv:Ro20T7Vg4rLHZ/040oUUrVE1bTxSorKAcOEUTSo6Vcg=,tag:apdRQL6eXYy2BC1qOgdKcw==,type:str]
  version: 3.13.3
