---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-5.1.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app syncthing
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 5.1.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: syncthing/syncthing
              tag: 2.0.16
            resources:
              requests:
                cpu: 1m
                memory: 64M
              limits:
                cpu: 500m
                memory: 1G
    service:
      main:
        controller: main
        ports:
          http:
            port: 8384
      listen:
        controller: main
        type: LoadBalancer
        loadBalancerIP: ${SVC_SYNCTHING_ADDR}
        annotations:
          lbipam.cilium.io/ips: ${SVC_SYNCTHING_ADDR}
        externalTrafficPolicy: Local
        ports:
          tcp:
            enabled: true
            port: 22000
            protocol: TCP
            targetPort: 22000
          udp:
            enabled: true
            port: 22000
            protocol: UDP
            targetPort: 22000
          discovery:
            enabled: true
            port: 21027
            protocol: UDP
            targetPort: 21027
    route:
      main:
        enabled: true
        kind: HTTPRoute
        parentRefs:
          - name: private
            sectionName: websecure-private
            namespace: networking
        hostnames:
          - syncthing.${SECRET_PRIVATE_DOMAIN}
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - identifier: main
                port: 8384
            filters:
              - type: ExtensionRef
                extensionRef:
                  group: traefik.io
                  kind: Middleware
                  name: oidc-admins
        annotations:
          gethomepage.dev/enabled: 'true'
          gethomepage.dev/group: Middleware
          gethomepage.dev/icon: mdi-cloud
          gethomepage.dev/name: Syncthing
    persistence:
      config:
        enabled: true
        existingClaim: syncthing-config
        globalMounts:
          - path: /var/syncthing
      immich:
        enabled: true
        existingClaim: syncthing-immich
        globalMounts:
          - path: /data/immich
            readOnly: true
          - path: /data/immich/.stfolder
            subPath: .stfolder
            readOnly: false
          - path: /data/immich/.stignore
            subPath: .stignore
            readOnly: false
      minio:
        enabled: true
        existingClaim: syncthing-minio
        globalMounts:
          - path: /data/minio
            readOnly: true
          - path: /data/minio/.stfolder
            subPath: .stfolder
            readOnly: false
          - path: /data/minio/.stignore
            subPath: .stignore
            readOnly: false
