apiVersion: v1
kind: Secret
metadata:
  name: envrouter
  namespace: envrouter
stringData:
  api-token: ENC[AES256_GCM,data:nZHeSPnBqb6QH1NDgmwmgJP3dAC0RUvss+16IDd2+2U26V0xok0jBFQ8op4WN69kZ2Lwep++cNJv0+w7ibOTGg==,iv:MfpCX4q3QytVNaMPhac+KczdUCxk0bj6dGEk18X5e/E=,tag:2lULwnd0wQBRHfLmUhjnkQ==,type:str]
  oidc-client-id: ENC[AES256_GCM,data:LRPZV1lVF84b,iv:sHgtI5XVNsortIxZ2NwjKoW0RXqoPGcAZpcGFvXS1o4=,tag:XZ7aHNaC13CMaqPdPAkX8w==,type:str]
  oidc-client-secret: ENC[AES256_GCM,data:OKlPbO0DYHQyKf/yaAuGKYiSDNZZct3von4qBLFR7lo=,iv:8HRK1unhE2Y9IsyIBnu7HrRggCXgbRZTJ5Pv9Vg7ORM=,tag:8atEKUwkCfFo1lTSoCgITw==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPN2VPZGNjbS92b3k1aXVD
        ZE9XZnZlMEQ1cGNkVzFOdGZDdzV4UnVlWG1zClZWSTZyNnJFcmtzSHRZWEpnSjVv
        YnQzenBDc1hkejRUOHpJTFBBWC9oK1EKLS0tIDZZeloySXd1NGZSdW12NzZ0Y2g1
        Q3lwUjJRdDBFVlBubEJWTURJdzB0RmsKtvFoszM4xUHWL3hJvcjj19fjJMfoOrPd
        YIKS0Xp6crqo57hP2/a6ZY8uIw7QJ/1t9+kmLriS4oOsOMrysbp4nA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
  lastmodified: "2026-07-08T08:22:00Z"
  mac: ENC[AES256_GCM,data:GlRqK4ckNRuu6NnwRTZ5w8bobx9VTYlfRGwHxcLRN7LrtPv+dsKwh8j/cLquGv0AZIzkgpQ8foohQU5dvf8RWhx38pYN3gb4JkIFVItxSI4ISY/zy20nJpleCkuvuuu5JH0GGWnTA6lW7w5dHX8mJSeHAIC9VOYDqSDqh1uH0Bc=,iv:NP5iRL3VrRoe20UD6c48pbgL6tLTMw8zGlKQnnAWW3Y=,tag:N6PwucqNhKGGyPWHC1V5JA==,type:str]
  version: 3.13.2
