# Certificate resource for cert-manager
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ess-community-turn-tls
  labels:
    app.kubernetes.io/name: ${APP}
spec:
  secretName: ess-community-turn-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - "turn.${SECRET_PUBLIC_DOMAIN}"
  privateKey:
    algorithm: RSA
    size: 4096
