apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP}-config
  labels:
    app.kubernetes.io/name: ${APP}
data:
  turnserver.conf: |
    use-auth-secret
    realm=turn.${SECRET_PUBLIC_DOMAIN}
    server-name=turn.${SECRET_PUBLIC_DOMAIN}
    fingerprint
    listening-port=3478
    tls-listening-port=5349
    min-port=49160
    max-port=49170
    cert=/etc/coturn/tls/tls.crt
    pkey=/etc/coturn/tls/tls.key
    verbose
    simple-log
    no-cli
    no-multicast-peers
    no-loopback-peers
