# Plaintext on purpose. Encrypt later if wanted.
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ${APP}
  labels:
    app.kubernetes.io/name: ${APP}
stringData:
  turnserver.conf: ENC[AES256_GCM,data:Oe5v4jU4ovV5J8EWR385k8SUoEkLT46/+ts1+/sOgPO+HpqapQ2hCul2OIxo58KJ03i2xu+55E46EnQ1y8SB+/8ezn/uNHNOoE51AWMFT/zfKKU+N8f5+2IkelPmkPie8gNQFYfL0UKrx7pAx+mriB3Opkem4c8GScH7CmyAslr2hgeVPeSaBwOGqo6UawEnH5vtNtCoFOSl+CtgG6JTaT49f83Oh7F/j4yujhOEE3fxEkzx7sU+A4vr4CAvMIJ11OQAAfJQFqFjxJ1x1ZXpWA4RVEKS/PeowyR+gLVvJKKMT4e+cTqeLcE+Q2tkBOhbsUOB1dXzi1hMlR0JGzmQ/iOlTKE2sbUP6kEyAVmt04eOFt2xsOmTCVtas8SLCuE8jMUJtvHLRSQ1UTYSW2QyvNJItChxUm+aOUVxGkc+oOP33r8dB78D92kmT6BEjs+8BmsI8KYEwYUu,iv:v1dZ/W7D47p4pR1Oojgtpszr2VlzysKe+HlSSn9D3+4=,tag:D/aLe82XegWwEU1X5sSPOQ==,type:str]
sops:
  age:
    - recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYzZ0VWJUTVNkakdBWWlq
        WjJTTUx5cVRUanF6TDdhcEVvNURnRTE1RUdNCnNidmorUTNDQmVWbGs0WEo1MW1P
        U0xQOEYxbk9CaG9BdmVHYlpxWmszWHcKLS0tIEZzN0d2RHI4SjdsNHBtM2YyUGpW
        eGloSHpnMTVtTE8rQVVWU0czdFVaOXMK7qx+QD2v1/psBE/o8MRfsfahZlPuno6I
        Hl4bVXWjUSMhaCX22pDc5HxSPje1Q5OGV3N3O2VWRlek2YEvY6htSQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-12T09:49:19Z"
  mac: ENC[AES256_GCM,data:zOq9vEBCYSCConbXNQD9bHIuyEwFp4SAeVlMv3HiGU1Dz85nWEQ17iPELVAOFxrsfajcbL5RkuJReEJGeTpujBKMKfXvGYavYzFZ9Ocd6eIgEMraOvvuLwShiUfXVDGz+Nne9Rd2Hkq0rRcggC7uLQdBdzjsZBDweyLAhqLZjr4=,iv:wXWOSTbNy5x9clycwZJC7nD4rd9DtNbKBVbZdjG5r9A=,tag:vFu2Tdrclq7fvKugPlaJ/A==,type:str]
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
  version: 3.11.0
