apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-secret
  namespace: games
stringData:
  S3_ACCESS_KEY: ENC[AES256_GCM,data:jxWRsJyuHmesbstiuFmicBJwhw==,iv:AHRqp4ryqyT3NzCyi4XJoOMkGISUMMj5lWx0OKeuZJE=,tag:tpKBDCz53Er6ez3Fv//7gA==,type:str]
  S3_SECRET_KEY: ENC[AES256_GCM,data:9NUdR1q0bD8cQGeUQaA1hXhXt05rvD0PJ4dVdIEA5GxnOwRlYlMdFg==,iv:yMH+D8Vx9i2dpkJ2ZkrTPcLXT3G181iLgXuwEoADEy4=,tag:Uh6fEHYGhAYDb/e8EG6enw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBY1doOGZQZFBheDZMbnRJ
        VWxUd1JBclpicVFVeTQ2ZitNTmJ2K2c3bmtBCnNhOG1HOHIwdEVtYzNZcHU2MWkz
        cTB6SXRTOGZzLzM1bkZaRWZ4SkR0R3MKLS0tIEd2OWpWdzI3NzIrVHFoRDA4akRp
        MVNMZkZ2SE4vWVV5UWphMkU5L0pGNUEKbzCbPLMFMOBgZVX/D8StIOFRd23PBC56
        UwwNNV5dgvkCttpfOyHboxj33Ux3QIUtdW/i/+knEby0HC5YFbc11Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
  lastmodified: "2026-08-25T16:21:25Z"
  mac: ENC[AES256_GCM,data:QtxlddmAE9ohTxTL/EmQv07QJcrhk9KPyw0ybzMbTQvLh2xDWaVqI9F5vbXeQ5DiEaj+1H+Dsloi+dL2IDvjWj/40F3BVLy86rBxMJNIbtn0jaxbzeBIezRrO27SBmwYR6bmzn4yJr+UNXRl1wdGSme+O0onWI6COyO95FM3pjk=,iv:n+JUvYJEh4MTrGUJ/7uHo5tdNpbWGQjK0bkF2Ugq2qg=,tag:e6sS3xms6r4J/RMb8dPM8w==,type:str]
  version: 3.13.3
