apiVersion: v1
kind: Secret
metadata:
  name: sigame-secret
  namespace: games
stringData:
  S3_ACCESS_KEY: ENC[AES256_GCM,data:zR9LVhaEOK0jqGc4NzxfdQ==,iv:W5gN8xHPu0Bd1or1VRMvQiiQS/+oR5CkPJO8cCpJs74=,tag:Nsk/BiWq7tL8PKl/aXSiVw==,type:str]
  S3_SECRET_KEY: ENC[AES256_GCM,data:6Lkqiq/2laR9Hbd3nmpneSKx96/AkpDtpjmpa2KZFtQZCbiIDd7Wmg==,iv:6s6NMATb8/YvktJgECJNuR7eeAqJe6cAGliPRm1irh4=,tag:3G7fs+yHISg/6xGTJtN6Kw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRd25WY1F6NHlRTGt1QXI2
        TkFtNkNtSUE5akc4YTl4ZlFKOW95b0E0N3hzCmJnT1ArNjFsb2Q1WDkxSXNwT2N5
        SEFTNVBGR3dBS01XVmhLLzhFVW8rdkEKLS0tIDdFUy8zY1ptZ3krMzk4ckFJUXh0
        M2FIR2tDZ050b1MwSlI3SW45V0IwaWMK0+5kTfxjkyBrXURUFkxHA18fYA2517dM
        kdvf/fHVhhb3nWMDfe4pH0RWZHjJiZPNQLsPsqvKhK/TSz38TO5bVw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
  lastmodified: "2026-08-25T18:41:32Z"
  mac: ENC[AES256_GCM,data:N4BL1DsYfqG/vdabvaLW5xJG4hEEVP4MK6jtn8Jj2kUDqRt/fuDu1fQ1sJT/8IsmmQZAwfuZB6cmw5j+J8Cm6k0bqrPucIszZIoh0BBwFKK/QL/xkz2UyHTsXfkU8Nnb4Y3pBkWvkPV4OoBx54fHB+fM3CJihSYo6IpLZvkHfqk=,iv:I2QNpNg/gqidzONFTvs/4UKwjDF6ddnOtBw+TlPmkzc=,tag:YWMvYR/RBBACoPwdqBqexA==,type:str]
  version: 3.13.3
