---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP}
  labels:
    app.kubernetes.io/name: ${APP}
data:
  config.json: |
    {
      "default_server_name": "matrix.${SECRET_PUBLIC_DOMAIN}",
      "disable_custom_urls": true,
      "disable_guests": true,
      "brand": "Cubly Chat",
      "permalink_prefix": "https://matrix.${SECRET_PUBLIC_DOMAIN}"
    }
