---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  cubly.override: |
    cubly.ru {
      errors
      forward . k8s-gateway.networking.svc.cluster.local:53
    }
