# Copy this file to secret.sops.yaml, replace the placeholder, encrypt it with
# SOPS, and add secret.sops.yaml to this directory's kustomization resources.
apiVersion: v1
kind: Secret
metadata:
  name: frappe-backup
  namespace: default
type: Opaque
stringData:
  access-key: ENC[AES256_GCM,data:9tCfFo0SdjCXQ5sx,iv:Fm9VJ4tb69SnxpErNJgzmZF4CY7Iu+/+e5jt4XcVuM4=,tag:TnR/08hs/8kFpV8bPfbymA==,type:str]
  secret-key: ENC[AES256_GCM,data:x3s1K9hP1e9WiRon/YhUyoR2S5u4+8ztYAR7DSBPVy4PGcPn/Tv7/g==,iv:eWmxhcMQtRXF3edrRBpTxYZwIno3BgZ+iOS47xKFkBM=,tag:R7icXcPdTyKkQgz9aHwrEw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBab0g1RzNHY2RFTkVFVm14
        a3d1R3lBdDJqWHcvU1p5K1d6UlJBSTkrMUFBCkhwWHI4ZXB0a0VQN2xCd3ZBYmNl
        K3dUanBORXZGVGJzWjNJTVNsTWtlQmsKLS0tIGVIeVo2RmhaYzJRMURhSlZmWFlm
        VHNLWkxjQlF3VGJJZG1tSlViT0xYNHMKB1u8otHesxKSYM/PVsashJFB0y7b/ira
        amFZzdfaJ/Wk36hfCXrYvfbVQrRlAWTYtXT9HBqOacxZX+tpgK4wrQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
  lastmodified: "2026-08-06T11:40:08Z"
  mac: ENC[AES256_GCM,data:9sfEFeyyyOtOT4AeJwSjANvnBBoURfw4thu2fz1Ft3k9yt6L/9x4n5a7ZPt5CtVZ/lzmWjemDma8aTlHcECjGXiFMzw559/vNXkIcmSkGf9QC4eZvJftsRNSEtMC5DAg40WnmX5P0k7evS4LRyFFeCs5/AmdjGwKXbs3ofPH4W0=,iv:O3y1U8LVnc8g4Gv8jwCqU0EOt/pIl1QQb/zhK9nFGVM=,tag:l5CyN8UPtdyIgwzrZUcMMg==,type:str]
  version: 3.13.3
