---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: ntfy-backend
  namespace: messaging
spec:
  weighted:
    services:
      - name: ntfy
        port: 80
        serversTransport: ntfy
