apiVersion: v1
kind: Secret
metadata:
  name: ${APP}
type: Opaque
stringData:
  APP_SECRET: ENC[AES256_GCM,data:hhNDG6ncUqPLAF/7ezZtTrEwYg8xjZsrnr4Z0KIB6KEhyqVSefJYU5Tlghc772tRyXOFQsGrILqzFsdgQ1g/cg==,iv:qeAL43QDu2I8ygSkYLp094U4gQktOjw4azGhL9EI75c=,tag:UGk9u+XZbYjJs2WdS2i7EA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRzlyV2dkazdVcWpqR0JI
        OWc5ZVBrcUkvM2VudVhCRkFEWnZ4VUZxNGc4CnpUWTVLeTlvLzRPOCtvcDlHN1pI
        UWViVlg0Y0VIc3pJazBSUklRN3R2SDAKLS0tIDJoNXlxVXQ2UE8xUjRCQ3dhcUZE
        TkM3SUtMcjZMUDNPZkJLTGp5dUlRQTAK6j+xtPovDED7kfZLf+wr4VvnQscy5rLG
        bqvJ9UEhZ4MHE1bGW9Q+k05ViZAEf6bg+k/BvuPYuwUXoQ58gG47Kw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
  lastmodified: "2026-09-21T14:18:59Z"
  mac: ENC[AES256_GCM,data:6ErQh1bqzECoF7jhleszLMQ71ztqjaK6Q3Qw8r5jawFFJiM+SYNSfoDy7KFPqdzlaJIDKdPm6NUmKnBmmLgVGGdeVWKPCM/dNEB4k45nnAnA2j2QimBJehVFbp2+yr0utZJf07RLrOe/r4/MEj/pPMQ/NmbfXZVzuFgUkuusoYo=,iv:PktNqy1a4Im2w/pAGjQM7wOYSsMgY7lUqvFtZvT2Zfc=,tag:EFW2yyEXally4L6YUw2c+A==,type:str]
  version: 3.13.3
