---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opencloud-csp
data:
  csp.yaml: |
    directives:
      child-src:
        - "'self'"
      connect-src:
        - "'self'"
        - 'blob:'
        - 'https://raw.githubusercontent.com/opencloud-eu/awesome-apps/'
        - 'https://auth.${SECRET_PUBLIC_DOMAIN}/'
        - 'https://update.opencloud.eu/'
        - 'https://tile.openstreetmap.org/'
      default-src:
        - "'none'"
      font-src:
        - "'self'"
      frame-ancestors:
        - "'self'"
      frame-src:
        - "'self'"
        - 'blob:'
        - 'https://embed.diagrams.net/'
        - 'https://docs.opencloud.eu'
        - 'https://auth.${SECRET_PUBLIC_DOMAIN}/'
      img-src:
        - "'self'"
        - 'data:'
        - 'blob:'
        - 'https://raw.githubusercontent.com/opencloud-eu/awesome-apps/'
        - 'https://tile.openstreetmap.org/'
      manifest-src:
        - "'self'"
      media-src:
        - "'self'"
      object-src:
        - "'self'"
        - 'blob:'
      script-src:
        - "'self'"
        - "'unsafe-inline'"
        - 'https://auth.${SECRET_PUBLIC_DOMAIN}/'
      style-src:
        - "'self'"
        - "'unsafe-inline'"
        - 'blob:'
      worker-src:
        - "'self'"
        - 'blob:'
