apiVersion: v1
kind: Secret
metadata:
  name: opencloud
  namespace: files
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:weC+2ciEp1N01dwihtQww0f1tu4=,iv:OAIQRz/eA59xbeprpsWXiE4Cg0Z5u9meI+tU+6C27b0=,tag:0LZO4JV8vmPEvC4WfJlMog==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:WyPFvi9qTtDZMjq4vJptDu22rLl72McaFf/aw7GMxBh1/yIKJm28K+vy,iv:c4ZASSdcX2daZ5U/iPF1TVIR+LxIs6EVHU/n8LtjtdI=,tag:1f3xYIrgl1Q+DfCEFDk4TA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlakdIZ2ZoOEkxVHowczRr
        cGNwMm9wbGgzZ0F5NnM5VWY2MVlJNThYalRZCjFnQmpkc2Y3dmR2ZTl5dmJVWlpz
        ZFR4WitpcmtrcTNtWWRXTndDNDA2QXcKLS0tIEtETVM2MVhXR1BHN0JNcTI1dHBo
        Qkk1QUhxenU1VEhVMDZ3RTFZWFpZRTQKh0FXs42F8YQMMNlfw+EpcpiPUD5RWcUo
        t6iJMk9DIADMftlxaYbg651VBmFoQWrMelJfZJBxM7NJ/7+Oc+Vi3Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
  lastmodified: "2026-09-17T13:41:31Z"
  mac: ENC[AES256_GCM,data:fWcrgYynkgWSxGcy5FY3fe4kRn4PybQP9LyAFOhDUgVDxXiDo4UcMTvrg2t6yq+JS0Uj34Dwf6pdbOY7Ay/0P4qi/t0ndtE5BdB9ykc+l4SkI8LoqFI2qvegXdgt9yATkl/fVyvtXlaKyig0iJdWmUtkfoU0CNHhzBH6ZN0HoB0=,iv:gg1lGaE7YSXPRDls8r81Xldor+FVMs8NGlN2+BzpiGk=,tag:B5cTWIJ3sbvECsLi5Ktofw==,type:str]
  version: 3.13.3
