---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seerr-config-v1
  namespace: downloads
  labels:
    app.kubernetes.io/name: &name seerr
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
