apiVersion: v1
kind: Secret
metadata:
  name: seerr
  namespace: downloads
type: Opaque
stringData:
  DB_PASS: ENC[AES256_GCM,data:sXKMKNMNYqna0z+8hotydBIa0Zm0jl7aAs/Gxyf9eHMsLToyLDrMZP8xtwOxbgJvHYbtpEjA+Su7M8op7xlRVQ==,iv:qmHZjX0V1hQTuE+pNSGTuo9zqp9HnDpJHG1eRYoRKIk=,tag:ypSaMnYRBXLV9cDJlWY63w==,type:str]
sops:
  age:
    - recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMREx2NFIyQVg5Wit6OHZw
        OXU4ODJLQ2JYU2IxVldDYTJ5UTMwcjFadUZFClM4bi9DNm9VY3FBVWxmK05vYVV1
        Z2s3RG5XQVhyV0wrb2t4a0QydW9wamcKLS0tIGh0bXo2UlluMHNxc2VROGkzbHlv
        QVowcFhUYUozVkNMVWZLY1BoNzhQYkUK8Tbn2yXq2nXt7e+TxxtOv+Kj8iiryE1N
        YMQ2s5eNq5Spqtk5v9e7FnXxbRqBDvJGsUvJO/yb0KEvWY4ZjC2qBA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T17:31:27Z"
  mac: ENC[AES256_GCM,data:ZXyKlxriBaCBW7nkjfiVM8JoEau23Bhe3QvlOaAi/zgQXPxbDZk2kaQGXNER32bq8BlvlbTQW4lv89JfRhK2GCs3ryffBs94PexS3OdU3ma/q2JmSQ75Tk5mOlBpDUF+FW4GzslHnQinLLUwc2NIJMrsjT+y2tfe/WzSUAEdvXs=,iv:CINhCoVKUqDpKK1mW3iyeBcK3hRLR/WpL38HLx6lcNw=,tag:aNVie2m02HcwTAZ8SR/ySA==,type:str]
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
  version: 3.11.0
