apiVersion: v1
kind: Secret
metadata:
  name: seerr
  namespace: downloads
type: Opaque
stringData:
  DB_PASS: ENC[AES256_GCM,data:iK4iMyEfd5SgGPsz0bAeBPOdObt920HuK/Qx7m13DKsTBoTIZZGO6bguYlVbrqIu2aZ6PN7BdUfJDOYk2LGAJw==,iv:NtfRgbD9HBuxiTR3qCFk1sG2+trGpIVUirvfqs8lJ3w=,tag:LRXogufl29mZ+msAaeGbLg==,type:str]
sops:
  age:
    - recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMTdZT2gvQVhqZUNmK3RF
        UkNzNVJBSDF6TTNEMHFQb0pLRlRqRUlTTDNVCllMNTFsaEpJTTVLL3lXMVhyYkp6
        LzJzbjdBV0RlcWVuYjh5VzZ1WXNaancKLS0tIGZteGk4QmdqbEZOVVFjVFlaRnZE
        dEx6NUZRMW1mNUh3YUJTeFhrbDdHUjQKwKNh/Uwh5oQ99g9YMZET6njLIOjYl2y7
        KsDKKVrL/beutUHFS80SPCMAqXNFHtlBLy9jJeUFkCHagul0lT4tlw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T17:20:16Z"
  mac: ENC[AES256_GCM,data:qoOLUDJ0KUoC2lHmyEZ/CAnPf+LWDqzLl7aNqt45jQhzyCNWdRrjSsxwYlZjjjaQRcqUl/tj67YbsX0nKeK05Zu+B4vF2jq+/J41aaC80pnFVLtdXBIGuHpciE8LGAsen0FeoI6SdnPsdkaUspPwQJZVFkHUUjPd8gRleJlDz/o=,iv:Rzhaq4kezxHs0C2VkFoJrVEZvygW2xYWkUhy+eiojLg=,tag:OQF8f67aijnljiZ/TpbKGA==,type:str]
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
  version: 3.11.0
