---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-5.0.1/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${APP}
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      terminationGracePeriodSeconds: 120
      securityContext:
        fsGroup: 4711
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault

    controllers:
      main:
        strategy: Recreate
        containers:
          main:
            image:
              repository: mornedhels/icarus-server
              tag: 1.0.0@sha256:a3d932c10dc042622ca234d8ac713e607b1f081701efe42e68f253c712ada67b
              pullPolicy: IfNotPresent
            env:
              SERVER_NAME: Icarus Server
              SERVER_MAX_PLAYERS: "8"
              SERVER_PORT: "17777"
              SERVER_QUERYPORT: "27015"
              SERVER_IP: "${CONFIG_ICARUS_ADDR}"
              PUID: "4711"
              PGID: "4711"
              UPDATE_CRON: "*/30 * * * *"
            envFrom:
              - secretRef:
                  name: ${APP}-secret
            resources:
              requests:
                cpu: 2000m
                memory: 6Gi
              limits:
                memory: 10Gi

    service:
      main:
        controller: main
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: "${CONFIG_ICARUS_ADDR}"
        ports:
          game:
            port: 17777
            protocol: UDP
          query:
            port: 27015
            protocol: UDP

    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        storageClass: local-path
        size: 5Gi
        retain: true
        globalMounts:
          - path: /home/icarus/drive_c/icarus
      game:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        storageClass: local-path
        size: 50Gi
        retain: true
        globalMounts:
          - path: /opt/icarus
