apiVersion: v1
kind: Secret
metadata:
  name: icarus-secret
type: Opaque
stringData:
  SERVER_PASSWORD: ENC[AES256_GCM,data:lATmPnM122laP/GPCw==,iv:OG4Hsw/JJJb7gG5W55UdbOVd8sEMcZUvjzyEH34gygs=,tag:QjwuaFju4Da7EJl/8hvJtQ==,type:str]
  SERVER_ADMIN_PASSWORD: ENC[AES256_GCM,data:YR0QZHhIPo7Xa6Nb3Gma94KyXNzEFjNpeVg3O1OAtKg=,iv:J5IJd85BNDx2H5qwXWqjAxxJII58NR+zCCVSTEmgoSM=,tag:DEqcfU1/GYf4duxKsKdb7g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VkREUU55dXhsODVZbzZm
        cjRmU0ZzSXUrQW9qenFlWWUvbkN2dHI3WmdZCnYyNytQTmpFaXB5cG12Y2c2Yk4x
        WTFnSE5TYjk2KzJSZVVkWTVjZjA4Z0kKLS0tIGNoSnVYaDZCcXJsVFk4WVVZQzdv
        NFVuUk10eUxMc2ZPc1RjVVZQdXJ2S3cK6w3y8xOs1QvVkT4nV2War36MNcgy4nU7
        XFoWSiSmCYxDaywV2fKoQ4j8X2iu27/9qhrdkitqUuZdxtdkjawrcA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
  lastmodified: "2026-08-08T16:43:07Z"
  mac: ENC[AES256_GCM,data:H8FYwjPbasPNfrVGTMc9DAS0rAFJc4rHX433ES3j16ft9YFK5qKo2CWkYZ2DZmdbxE4sDxHCLn05RLL7YdQBS+X0xc/YwK1w5VkfQGyk40nNmxJQEuK6YsD7XjV/crjB2kd01l7PgLe30jRuGEAnnHlI20bapvFHEuMsmXg+jWg=,iv:3LlrhxuBV9meBVlcO7ewTwEeyLSwOGli2CwNCkpA+7U=,tag:b5BR0Hlm3z6yRCqT75gYtg==,type:str]
  version: 3.13.3
