---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - services.yaml
  - gateways.yaml
  - certificate.yaml
  - ingress-classes.yaml
  - tls-store.yaml
  - middlewares.yaml
  - canary-routes.yaml
  - dashboard-route.yaml
