---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: crowdsec
spec:
  plugin:
    crowdsec-bouncer:
      enabled: true
      crowdsecMode: stream
      crowdsecLapiScheme: http
      crowdsecLapiHost: crowdsec-service.security.svc.cluster.local:8080
      crowdsecLapiKey: ${SECRET_CROWDSEC_NGINX_BOUNCER_API_KEY}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: private-allowlist
spec:
  ipAllowList:
    sourceRange:
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
      - 127.0.0.1/32
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authelia
spec:
  forwardAuth:
    address: http://authelia.security.svc.cluster.local:8000/api/authz/forward-auth
    trustForwardHeader: true
    maxResponseBodySize: 8192
    authResponseHeaders:
      - Remote-User
      - Remote-Name
      - Remote-Groups
      - Remote-Email
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: echo-cors
spec:
  headers:
    accessControlAllowCredentials: true
    accessControlAllowHeaders:
      - DNT
      - User-Agent
      - X-Requested-With
      - If-Modified-Since
      - Cache-Control
      - Content-Type
      - Range
      - Authorization
    accessControlAllowMethods:
      - GET
      - PUT
      - POST
      - DELETE
      - PATCH
      - OPTIONS
    accessControlAllowOriginList:
      - "*"
    accessControlExposeHeaders:
      - Content-Length
      - Content-Range
