{
 "title": "iPerf Dashboard (Public)",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "grafana-postgresql-datasource" },
   {
    "name": "test_id",
    "label": "Test ID",
    "query": "SELECT MAX(id) FROM iperf_logs;"
   },
   {
    "name": "host_filter",
    "label": "Host",
    "query": "SELECT id || '___' || COALESCE(alias, host)\nFROM iperf_hosts \nORDER BY host"
   },
   {
    "name": "second_host_filter",
    "label": "Host 2",
    "query": "SELECT h.id || '___' || COALESCE(alias, host)\nFROM iperf_hosts h\nWHERE (\n    CASE \n      WHEN '0' IN ($host_filter) THEN false\n      ELSE (h.\"id\" NOT IN ($host_filter))\n    END\n)\nORDER BY host"
   }
  ]
 },
 "panels": [
  {
   "title": "Host 1 avg. speed",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  l.\"created_at\" AS time,\r\n  l.\"average_speed\" AS value,\r\n  COALESCE(sh.\"alias\", sh.\"host\") || ' -> ' || COALESCE(th.\"alias\", th.\"host\") AS metric\r\nFROM iperf_logs l\r\nJOIN iperf_hosts sh ON sh.id = l.source_host_id\r\nJOIN iperf_hosts th ON th.id = l.target_host_id\r\nWHERE\r\n  $__timeFilter(l.created_at)\r\n  AND (\r\n    -- host_filter: matches either source or target\r\n    CASE \r\n      WHEN '0' IN ($host_filter) THEN true\r\n      ELSE (l.\"source_host_id\" IN ($host_filter) OR l.\"target_host_id\" IN ($host_filter))\r\n    END\r\n  )\r\nORDER BY l.created_at"
    }
   ]
  },
  {
   "title": "Host 1 <-> Host 2 avg. speed",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  l.\"created_at\" AS time,\r\n  l.\"average_speed\" AS value,\r\n  COALESCE(sh.\"alias\", sh.\"host\") || ' -> ' || COALESCE(th.\"alias\", th.\"host\") AS metric\r\nFROM iperf_logs l\r\nJOIN iperf_hosts sh ON sh.id = l.source_host_id\r\nJOIN iperf_hosts th ON th.id = l.target_host_id\r\nWHERE\r\n  $__timeFilter(l.created_at)\r\n  AND (\r\n    -- host_filter: matches either source or target\r\n    CASE\r\n      WHEN '0' IN ($host_filter) THEN false\r\n      WHEN '0' IN ($second_host_filter) THEN false\r\n      ELSE true\r\n    END\r\n  )\r\n  AND (\r\n    (l.\"source_host_id\" IN ($host_filter) AND l.\"target_host_id\" IN ($second_host_filter))\r\n    OR\r\n    (l.\"target_host_id\" IN ($host_filter) AND l.\"source_host_id\" IN ($second_host_filter))\r\n  )\r\nORDER BY l.created_at"
    }
   ]
  },
  {
   "title": "Latest results",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  l.id,\r\n  l.created_at,\r\n  COALESCE(ih.alias, ih.host) as iperf_host,\r\n  COALESCE(sh.alias, sh.host) as source_host,\r\n  COALESCE(th.alias, th.host) as target_host,\r\n  l.average_speed,\r\n  l.second_measurements\r\nFROM iperf_logs l\r\nJOIN iperf_hosts sh ON l.source_host_id = sh.id\r\nJOIN iperf_hosts th ON l.target_host_id = th.id\r\nJOIN iperf_hosts ih ON l.run_on_host_id = ih.id\r\nWHERE\r\n  $__timeFilter(l.created_at)\r\n  AND (\r\n    -- host_filter: matches either source or target\r\n    CASE \r\n      WHEN '0' IN ($host_filter) THEN true\r\n      ELSE (l.\"source_host_id\" IN ($host_filter) OR l.\"target_host_id\" IN ($host_filter))\r\n    END\r\n  )\r\nORDER BY l.id DESC\r\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Per-Second Speed - Test ID: ${test_id}",
   "type": "trend",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  (series.ordinality - 1) AS second,\r\n  (series.value)::numeric AS speed\r\nFROM iperf_logs l\r\nCROSS JOIN LATERAL jsonb_array_elements(l.second_measurements->'data') WITH ORDINALITY AS series(value, ordinality)\r\nWHERE\r\n  l.id = ${test_id}\r\nORDER BY second"
    }
   ]
  }
 ]
}