apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-secret
stringData:
    config.py: ENC[AES256_GCM,data:ubjnHyn0sinVWNSmjAMOLVbUWDfN5tpYPubkKALiFChAbdZ/gT+PzgghJDEdxCsDifrMiSq7tYjCkkyRWUrQFAzsm1Sd4pIZ6OFThORZT5MsI5yoqCGenAm6hXOLf3e2ShIX8libt+HU0R7dd06H708pOujBZvDYYoK3iOgsRgKPIeNeu1hLwT7oh4cuAaHPACIpPzXg210eA7J6yuSs9VnAAGBfgquGHTZdhPhFgHw1VtKLNKGb99YitGA4gYqJ4a1pNN9uJ9upJJUApQlpp8RWV0g7QKqYJkGf+fREyLccQEYL/W0xm+FSXP7H5LjizpjI7NzLB3fNgxlgnSv5xTZTm5T8pfBnNttGh2mIDGya2SjT9WUDhf2ufNLQToHmiq13jWOFaMVERoitPFvgmpHQcFtGs609rjr6w3mZ7/bNILEOlKArEZgi288MjAE/IaBBMMiPIYuhYnlMx7I10MBX5MMZ8Kh0TeuQEPGEgpDCv5LU7xdXBy8okXGiIdxnquoqwq+QICHJHK78pe4f4hQOI8o+cl3XC1lE2ImAzNfXIJGiBtJICKuxpz/8Va1+LESYweGAchgyEFiB+u4jftSOFA==,iv:zvfhsHVnEyQSH+o/sjRcalDBNZe5PdgnZC87ZCU2m1E=,tag:fDqldR6KsmqT1qp0/4+xkg==,type:str]
sops:
    age:
        - recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aHNQMCtxU0w3SERWMVFN
            QlQwaFBXbVNzNklwdG5NTXdSdnZvejNuY0U4CmVuTmZaci92TXp5UkxYMnd5dmhi
            RTFaYmVpSlFuaFFjbVp0cVFxejQrR3MKLS0tIExZMU5MNUNROWRhUW0zdEJ6OU1X
            RmRzUisyVzZXcXo5V2R4Yi93NkVieTAKCIz0cKH+oqtuoaLuUPRSA0TPzmSX8h1g
            0JWe1/TLc7to02h1ATtTK0z9wq16gAM5mzT9rGnBXkNhKWa5Hid06Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T00:35:54Z"
    mac: ENC[AES256_GCM,data:qKgbyTQq72xGicvlLY96phYahH6CuS9iQMTiM9ooCEg2EJ5kF0Cbq2o8jmdXYXEliZosc5TYfIgzDvfnnJRiuKmFg2llAwiDinaLa4dGyHjXdIdAmJRXEOEcRKub/qRDML4wsBrQ4RNqybMeGVyWxTV1iOpH1rqLn5nQG0ULe8k=,iv:zNU9Y8Imj8k3tsboLK0PDawlS7inE9DZDhGVjXplqRo=,tag:at3z5LBBOp7wHRi2Pn6qMQ==,type:str]
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
