apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-secret
stringData:
  config.py: ENC[AES256_GCM,data:wiGugRV3S6o2qfrTiQrBOjURfXU+KepWhMO2dWNszhLCWNfGxUeWq9TNPiXsBqsExgjhZcESlkYQjFCiZiwmatKDkAn5IISmKUjdwU5vVOd8RmXseh1zd6Qc6FrWCUR0eRXaP3S0f7ivVbmNt2p/2FEuSiX58PwW286LE+iiws4EQOgERtqv7u0jK5VZitrwYE2+XdLaMEeDd2FpFaiE4WkQs6WtF48tSbbeRbkrsCQSNH6faNZIl74kidjztpLYh+Fpxd5glheQI5JexS/Fhj2hSYAaQzdXRYplFWVE4v/mg8LPCBTGs58+FrYoQ7xormGL+dpW5ffl+yXdOWkC7lrR9N5q/DPuDz5ivAIU4PSgYusrDx+S4YbjLFPd65oHhsLKYFDON8S+LpqVYOUBmxLA6yILRowl8Ill+U/VDTjS+GCvlqmCXkej6vXvovD3snQjIisEdNOPjDGetwUYodL4K0nNyDwRGPeIHOfb3+rLDQgdHguUnPT/Kg3UzEsh5HMbia7mCO9x2eoOKK15G4rPF4LNy7jaY7FRY3Vmwh3qe1KRtQDQBMERoSyC+btBzyCpH/9D8UvyOd8=,iv:zuxKKDDJeFzOG+54YKhEqdCQksMzdcBWsfX196kSwGE=,tag:ZvCdnqGBSc00egUZgNfu8Q==,type:str]
sops:
  age:
    - recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aHNQMCtxU0w3SERWMVFN
        QlQwaFBXbVNzNklwdG5NTXdSdnZvejNuY0U4CmVuTmZaci92TXp5UkxYMnd5dmhi
        RTFaYmVpSlFuaFFjbVp0cVFxejQrR3MKLS0tIExZMU5MNUNROWRhUW0zdEJ6OU1X
        RmRzUisyVzZXcXo5V2R4Yi93NkVieTAKCIz0cKH+oqtuoaLuUPRSA0TPzmSX8h1g
        0JWe1/TLc7to02h1ATtTK0z9wq16gAM5mzT9rGnBXkNhKWa5Hid06Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-19T00:28:03Z"
  mac: ENC[AES256_GCM,data:2sIwxly1qz5L2s/d0t9p8G2m6Jq13wtYXTOblQ4ZrLQrr6rv45eop+B5QV94Gwl+sGEt9HP01fuyeN7Q5T6dAOBpi6mUppydK0CSiJ5FOkHYahG58ha+iIx3q+ozTz2PlJ/M0eM59FnQVLSUv5cdw115Qye1ECJszY8o4E6rtnU=,iv:iXLnKpGPa5dHEvq8Q1ZpyiM9HEiUZS/mGAEAxajtrmo=,tag:9GeAns0xGWuEkUyA60xbZg==,type:str]
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
  version: 3.11.0
