apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-secret
stringData:
  config.yaml: ENC[AES256_GCM,data:foltk9/9mULI6uPC47NAbKabzuooHY35XWq5UKHY1t9bsgK6vZSRDfEmkqB9PktuNAH7vISC/Psj3yi/0ApLOR2kphLRbu6XspvrtthSy1pnAWZPBXZdcjqkJBsMfFxTMltyRr39cjUIYj402lXeHWAl4ewwV3O5nQjgEGx00EYYOfDoiuflQIk/lzc2E34gDCRKBRkjxQIe1k6a1zR7+5yoVuUES2hH4FQI5qJkH1Ca2b3Uo2jmeicuyYZgWb569J0O3YdSWByvuhlYVahoNOMhB4BlvnQetoP5t56N9qXXmEW7RLRTU7I08E0y6MvtfGt5zXfVLGTGPgB/rbmeG65HZgA9MsFeWv214ko8ljkCmIXy2RRS+n178NeBGVgF8u/POt1ntw==,iv:ohvS/DKbP06QGckyIPHPm5xpbVKV90hDfJkh7DKfZ1o=,tag:iRnVhpEEFWlcJgvvdOOHsA==,type:str]
sops:
  age:
    - recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcjB0UU91M0E1MngxNnJR
        Z2RmY1oxaWVrZ1BuVThXa1Z4OU1Qa3RaQ0NvCnNNaDN5eWQvRzBmQ0ZJZEJ2WmU0
        WHUzMGlOMkJqT1NnNlJqZUcrMTQvdFEKLS0tIFNzSTZtVTFtbXcwbHV4MHNjdW9Y
        YVg5VHZZMHhzVkdGS3NzSjFib053TUUKOIFzLGSGVkA0TxkLIijW5xDMkS5RLHOg
        5LABcJneL3cPUjyto85JAI5hJzAU84Wof0QQFOJQAq0eGhjbRJGTuw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T23:53:08Z"
  mac: ENC[AES256_GCM,data:4fSnj2GpNKFRexD7/i0rDwTxrVfxVJh0IdjLB4CqcREHyfzhRh2DlFyHr0S6b6qnGF/lpZt1ia+96XowT5BGOLwSdBhm8vX4vVpRyPmEpMQYWQYyeXTgJB/a6i78MngJVl9EvBfILf2qepVEF8ryysGp7lWZbW0tuC3FQgYaHc8=,iv:h0FV1wlVBtmVK6V9rBftdpYpuD3Nt48Qpv33vCvQl48=,tag:dvdUBLGlxOvAslw5xAey0g==,type:str]
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
  version: 3.11.0
