---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - secret.sops.yaml
configMapGenerator:
  - name: llama-cpp-download-model
    files:
      - download-model.sh
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: llama-cpp-models
    files:
      - models.ini
  - name: llama-cpp-install-dartai
    files:
      - install-dartai.sh
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
generatorOptions:
  disableNameSuffixHash: true
