apiVersion: v1
kind: Secret
metadata:
  name: ${APP}
  namespace: ml
stringData:
  LLAMA_API_KEY: ENC[AES256_GCM,data:yAt9VcKQqbOR1OhrCV48Pj7lon41SycKWCK8eO9xsP+75/0eIJt8LZxAYFkiWz6tx0NN+tYh6VjmLNdTqz3uAQ==,iv:FZIBUbID9Lgc6NJLenYTem+JnJBIPIyLq9ePU4ri10k=,tag:08ZmuxuIrRjrfqB5Q+cWtQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwczFMRTJ5UVBWWjBJVklC
        OEdRWUxBWUJoR1hMaGlzdDR4YjJHRmprUTFzCk1mTGx0V3ZjUEhESWRId2orQUJB
        TnFXM0IvMURobmRvUlNaekwvSWVRQ28KLS0tIFhnOWhvMytBd05JQk9mVmRlK0Rs
        NGlNVlVwZmt6VHpOc0sybFA0d04wQncKjOGJx5x3zbDxuOXoZuKPrtAK1NjCJb5E
        sO8hB90oDUWHRQql44NbBMvJTzl+pygScx0SAKrS6ztvJWhmulpp2A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
  lastmodified: "2026-09-28T13:33:18Z"
  mac: ENC[AES256_GCM,data:J55c+wMjFl4SCH04sGfjfi8v0JldnTaKaktqIKYlACDlCiC2rYHqG/B21sY5PsNNjUewN/aSDsKu+Wo7s48ysFCTQt+7imHmyJAaOJklIgks+Z2DxiEbJOQBk20oT4e/ke5hy4jClJTfRe6Ulhb5mA7SGzcZz4/Ts255rCOK7aE=,iv:jtTOyi9eplLxlW/FZ0I++3M+pfoAZQ0WRnJ0bx9skMo=,tag:OAQOtrSryGdsT7scDVhfjA==,type:str]
  version: 3.13.3
