# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-5.1.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${APP}
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      nameOverride: ${APP}
    service:
      main:
        controller: main
        ports:
          http:
            port: 80
    route:
      main:
        enabled: true
        kind: HTTPRoute
        parentRefs:
          - name: public
            sectionName: websecure-public
            namespace: networking
        hostnames:
          - '{{ .Release.Name }}.${SECRET_PUBLIC_DOMAIN}'
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - identifier: main
                port: 80
            filters:
              - type: ExtensionRef
                extensionRef:
                  group: traefik.io
                  kind: Middleware
                  name: authelia
        annotations:
          external-dns.kubernetes.io/enabled: 'true'
          external-dns.kubernetes.io/target: ${INGRESS_DEFAULT}
          external-dns.kubernetes.io/cloudflare-proxied: ${quote}${INGRESS_DEFAULT_CF_PROXY}${quote}
          gethomepage.dev/enabled: 'true'
          gethomepage.dev/group: Media
          gethomepage.dev/icon: /icons/radarr/${HOMEPAGE_ICONS_COLOR}
          gethomepage.dev/name: Radarr
          gethomepage.dev/pod-selector: app.kubernetes.io/name=${APP}
          gethomepage.dev/widget.type: radarr
          gethomepage.dev/widget.url: http://radarr.downloads
          gethomepage.dev/widget.key: ${SECRET_HOMEPAGE_RADARR_API_KEY}
      api:
        enabled: true
        kind: HTTPRoute
        parentRefs:
          - name: public
            sectionName: websecure-public
            namespace: networking
        hostnames:
          - '{{ .Release.Name }}.${SECRET_PUBLIC_DOMAIN}'
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /api
            backendRefs:
              - identifier: main
                port: 80
        annotations:
          gethomepage.dev/enabled: 'false'
    persistence:
      config:
        enabled: true
        existingClaim: radarr-config-v1
      media:
        enabled: true
        existingClaim: radarr-downloads
        globalMounts:
          - path: /media
    defaultPodOptions:
      annotations:
        reloader.stakater.com/auto: 'true'
      securityContext:
        runAsUser: 777
        runAsGroup: 777
        fsGroup: 777
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/home-operations/radarr
              tag: 6.4.4.10684@sha256:dc66c010c5d9a0ea131fa3c1716fd0f9493b64c1d3d9f938ebed6b7fab580e5b
            env:
              TZ: ${TIMEZONE}
              RADARR__APP__INSTANCE_NAME: Radarr
              RADARR__SERVER__PORT: 80
              RADARR__APPLICATION_URL: https://{{ .Release.Name }}.${SECRET_PUBLIC_DOMAIN}
              RADARR__LOG_LEVEL: info
              RADARR__POSTGRES_HOST: homelab-pgsql.database.svc.cluster.local
              RADARR__POSTGRES_MAIN_DB: radarr
              RADARR__POSTGRES_LOG_DB: radarr_log
              RADARR__POSTGRES_USER: radarr
              RADARR__AUTH__METHOD: External
              RADARR__AUTH__REQUIRED: DisabledForLocalAddresses
            envFrom:
              - secretRef:
                  name: ${APP}
            resources:
              requests:
                cpu: 1m
                memory: 250Mi
              limits:
                memory: 2000Mi
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: 80
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
