---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-5.0.1/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app flaresolverr
  namespace: downloads
spec:
  interval: 30m

  chart:
    spec:
      chart: app-template
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  install:
    createNamespace: true
    remediation:
      retries: 5

  upgrade:
    remediation:
      retries: 5

  values:

    global:
      nameOverride: *app

    service:
      main:
        controller: main
        ports:
          http:
            port: 80
            targetPort: 8191

    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/flaresolverr/flaresolverr
              tag: v3.5.0@sha256:139dfee1c6f89249c8d665d1333a42e8ec74ec0a86bc6bb1c8461e10d3a66a47

            env:
              TZ: "${TIMEZONE}"
              LOG_LEVEL: info
              LOG_HTML: "false"
              HEADLESS: "true"
              PORT: "8191"

            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              privileged: false
              readOnlyRootFilesystem: false
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault

            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 2Gi

            probes:
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 8191
                  periodSeconds: 5
                  timeoutSeconds: 5
                  failureThreshold: 24

              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 8191
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 3

              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 8191
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
