apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authelia-chain-default
  namespace: flux-system
spec:
  interval: 30m
  path: ./cluster/apps/networking/traefik/authelia-chain
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  targetNamespace: default
  dependsOn:
    - name: traefik-crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authelia-chain-downloads
  namespace: flux-system
spec:
  interval: 30m
  path: ./cluster/apps/networking/traefik/authelia-chain
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  targetNamespace: downloads
  dependsOn:
    - name: traefik-crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authelia-chain-flux-system
  namespace: flux-system
spec:
  interval: 30m
  path: ./cluster/apps/networking/traefik/authelia-chain
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  targetNamespace: flux-system
  dependsOn:
    - name: traefik-crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authelia-chain-home
  namespace: flux-system
spec:
  interval: 30m
  path: ./cluster/apps/networking/traefik/authelia-chain
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  targetNamespace: home
  dependsOn:
    - name: traefik-crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authelia-chain-kube-system
  namespace: flux-system
spec:
  interval: 30m
  path: ./cluster/apps/networking/traefik/authelia-chain
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  targetNamespace: kube-system
  dependsOn:
    - name: traefik-crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authelia-chain-ml
  namespace: flux-system
spec:
  interval: 30m
  path: ./cluster/apps/networking/traefik/authelia-chain
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  targetNamespace: ml
  dependsOn:
    - name: traefik-crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authelia-chain-monitoring
  namespace: flux-system
spec:
  interval: 30m
  path: ./cluster/apps/networking/traefik/authelia-chain
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  targetNamespace: monitoring
  dependsOn:
    - name: traefik-crds
