---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app
  - config

configMapGenerator:
  - name: traefik-captcha
    files:
      - captcha.html=resources/captcha.html
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled

generatorOptions:
  disableNameSuffixHash: true
