apiVersion: v1
kind: Secret
metadata:
    name: mcphub
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:y4q1F8yRQruP0QOqmV98uRW1e6A44ULBR/l10Wy3,iv:5bcxsqR6PtGR7062XyOhMlh04HLzSCIYo5xQrHGR3wY=,tag:gK9xqDXl02caLpJsRQl9qQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:ZT+T4UeQG53nxSiC3kb/hlfqPILx1b5vnSBox/sKusk=,iv:YKZHVxOMPAhx/avrR4lIF8OOCv5qWR47dzfKyfmQm+g=,tag:6V1Mw3OnCRggJhVd6f31yA==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:0iO6nJe/8MhWX+9I9ALmE1xxj/+Lj4DI9QdfYMX73V4=,iv:MdHv55eRlV5/jJG3/4RALLBHiMn7hsprUI3S+yr3UZs=,tag:EmT9FELMYB8dZGc/xRPnjg==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:F4S2wTeOQA+fEBj7hutFmoVtS2TJ537cTpJugYNoT4bbzxtX59kU78YmF8GZ4eulbQAlZoY/9xTDYhqA2Qh9GQ==,iv:DU6mj4rriaoq/2cOp/pb/71Kjrtwo9m5vu84htFDbJA=,tag:jzZGwAYJsgSNA3jtaBQV1Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIK2RjazdHVW1tL1dVR05Z
            YVJHSmNWRktubVhZaFlHZkNpdHRDY2NwMEVJCkdYY1BOem9PK2VNUnRqV0dPOUJx
            aUNaWEkzWVhiaklrakE2WDBrbngxNTQKLS0tIE9XaTM2VEFHbHplRTNyUEtZMVJu
            YXB2NCtpbmN3dS9kZERCZnNzVnA2dGMKrqrWCSuRHv3hkG6D9fnWoTnjlR2NMj8q
            ruZMeWMey0zL2JosevaOQXsPyfTVBbw+R2JKVDDsIpSgqCdVYOJGkw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-28T11:23:29Z"
    mac: ENC[AES256_GCM,data:dGR85vQscThAeCCAwypVTpfjADxE7JIVbG/MmOpFymgULt7IwZqmplxadN9Xz8Ov5KanWVCOKbchhNil3+FMBkYEZcUL1qKwFNRORdF9ZoXom3TJ7Y2+FXENeuA1AfFT8bPY4tQDogRzH0+t1+i0Wq0q/r59zbnX58akSjuvUrY=,iv:LT9/Qm/QZmFSpMEPcZ3mTEMWmPHLyoEM4SNFl+Sfy0A=,tag:Or8ftgPrWOZmLbV8RGpTkw==,type:str]
    version: 3.13.3
