apiVersion: v1
kind: Secret
metadata:
    name: mcphub
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:y4q1F8yRQruP0QOqmV98uRW1e6A44ULBR/l10Wy3,iv:5bcxsqR6PtGR7062XyOhMlh04HLzSCIYo5xQrHGR3wY=,tag:gK9xqDXl02caLpJsRQl9qQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:ZT+T4UeQG53nxSiC3kb/hlfqPILx1b5vnSBox/sKusk=,iv:YKZHVxOMPAhx/avrR4lIF8OOCv5qWR47dzfKyfmQm+g=,tag:6V1Mw3OnCRggJhVd6f31yA==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:0iO6nJe/8MhWX+9I9ALmE1xxj/+Lj4DI9QdfYMX73V4=,iv:MdHv55eRlV5/jJG3/4RALLBHiMn7hsprUI3S+yr3UZs=,tag:EmT9FELMYB8dZGc/xRPnjg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIK2RjazdHVW1tL1dVR05Z
            YVJHSmNWRktubVhZaFlHZkNpdHRDY2NwMEVJCkdYY1BOem9PK2VNUnRqV0dPOUJx
            aUNaWEkzWVhiaklrakE2WDBrbngxNTQKLS0tIE9XaTM2VEFHbHplRTNyUEtZMVJu
            YXB2NCtpbmN3dS9kZERCZnNzVnA2dGMKrqrWCSuRHv3hkG6D9fnWoTnjlR2NMj8q
            ruZMeWMey0zL2JosevaOQXsPyfTVBbw+R2JKVDDsIpSgqCdVYOJGkw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-28T10:36:50Z"
    mac: ENC[AES256_GCM,data:47ugrS8nZeRKJ0RUp6oXuI8yBsk2MgUqEg1esZY8lWrP3juD+OmzE0Ub6sp2ssFfpeiUuMqpaWKv75ChuIX0ner/x67tofc9KQ4euE1qjoXnUEvwyLKIiNLvA1x9Do1tC5ZqxgBYiT7kVtDDiWXqPIb7ES63bKc9raLxboZ1sxk=,iv:LyUsAtkoMVtZocQw9sCo/0vdFSxF0SU4vAr/tHMcZPY=,tag:ubZpTQNvnTdfNpJXv4r5Cw==,type:str]
    version: 3.13.3
