apiVersion: v1
kind: Secret
metadata:
  name: mcphub
stringData:
  ADMIN_PASSWORD: ENC[AES256_GCM,data:y4q1F8yRQruP0QOqmV98uRW1e6A44ULBR/l10Wy3,iv:5bcxsqR6PtGR7062XyOhMlh04HLzSCIYo5xQrHGR3wY=,tag:gK9xqDXl02caLpJsRQl9qQ==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:ZT+T4UeQG53nxSiC3kb/hlfqPILx1b5vnSBox/sKusk=,iv:YKZHVxOMPAhx/avrR4lIF8OOCv5qWR47dzfKyfmQm+g=,tag:6V1Mw3OnCRggJhVd6f31yA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIK2RjazdHVW1tL1dVR05Z
        YVJHSmNWRktubVhZaFlHZkNpdHRDY2NwMEVJCkdYY1BOem9PK2VNUnRqV0dPOUJx
        aUNaWEkzWVhiaklrakE2WDBrbngxNTQKLS0tIE9XaTM2VEFHbHplRTNyUEtZMVJu
        YXB2NCtpbmN3dS9kZERCZnNzVnA2dGMKrqrWCSuRHv3hkG6D9fnWoTnjlR2NMj8q
        ruZMeWMey0zL2JosevaOQXsPyfTVBbw+R2JKVDDsIpSgqCdVYOJGkw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
  lastmodified: "2026-07-17T20:37:09Z"
  mac: ENC[AES256_GCM,data:o7pmeXPJwemYXyanDne/Fwj3ukqCwCgSKX35zNPvWUc2R5HhAzzj4ND2SRFUBilcPE994vKK7GeJVmNFD0Clmn9kofnuDnbB/2+BRiA/MQGgdhI1XmFBLSLyEvYx1sy3SWDDa4vn3OBEc7ZCZywhlUX9Fsk3xcnehfcEWGuFvwQ=,iv:ciWcVzuy9G7MmknF4+auL/Lu6OMkk22ND+jMAiax3Ds=,tag:ZJo+IkrHfJalEDkghHGOog==,type:str]
  version: 3.13.2
