---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: paperless-admin-deny
spec:
  ipAllowList:
    sourceRange:
      - 0.0.0.0/32
      - ::/128
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperless-admin-deny
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: default_paperless-admin-deny@kubernetescrd
    traefik.ingress.kubernetes.io/router.priority: "100"
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: paperless.${SECRET_PUBLIC_DOMAIN}
      http:
        paths:
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: paperless-app
                port:
                  number: 8000
