apiVersion: v1
kind: Secret
metadata:
    name: litellm
    namespace: ml
type: Opaque
stringData:
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:M0joXzoHnZ80ZL/Dn7o7DnuFcTr8OUqMdULWW+D2X154uXo=,iv:6QGM/NTxAhu1NfQoBGXFw3itF+fMH7L3o7mneTnGeCk=,tag:Pj9fveOBIXwunYpijIqoKg==,type:str]
    LLAMA_PC_API_KEY: ENC[AES256_GCM,data:6d/q6Ono2Besoa8ptVJv42G2wMsTR5T84nU6MkWHB3kctM8CbvThSaXFwwKkV0/MoIoFLI3hvusPx73xz6siqA==,iv:oUsmXd2ZjGyY9ibGR8rpghnJCVcQHcivMbNPInZpH3U=,tag:24IX6Abz93rv9dYydeqbQA==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:ZNYvVBj5y4xQlSI97sBmukATqKpUxk7N+82wrEKVyfw=,iv:GY28R4RrheApVVTuXUMUSTX4ev2OOgkmHIyc4wylF+4=,tag:NB0nPjHFuYaDnubkM4kUoQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVFp1NWFPNU4xODNrMWdI
            VGszbU1yWXFxTVZOTjNQeFdoWElKamt5VmlRClZhLzB0bXZwb2VrVmpWZ0ZnUm5D
            NXV2ZERJUE16UDN3dlYvZVJIM0VRZ0UKLS0tIERCODd5OUN1TEtVelN1VXVyeDVp
            MFh5a0FHcDNBRXo5eXZGOE1iM2hOWW8KmdomJ1G2PD76TR2vFSqMfXQiwxuDQITT
            B/1MC49xXsP+pA2gZlMoYSfkL33EjL78sHguwMNPbK+7vhdBIqszpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-29T20:13:58Z"
    mac: ENC[AES256_GCM,data:fbifcq1J+S4mH+r/ok7bgln1eAeu7PnkaOE51yeRsTkT75hIastr+6wVS7Gs/ldlBOnP73zZGMzSF6x9B0dCVvS/C/0awRcPnLhobSwmPjy9qbjkfsOE3hXXfSO4bqp5hG7JGisxwKhixucXjcOZT3dgP9SuHZhAKS0gh+Ctjuo=,iv:J34vbrd0FEUlBwlYlgV5g4x+bwXFpEg331VNssNVGuc=,tag:+dqaD2gT81HsJyAGqHbSvQ==,type:str]
    version: 3.13.3
