apiVersion: v1
kind: Secret
metadata:
    name: ${APP}
type: Opaque
stringData:
    BIFROST_ADMIN_PASSWORD: ENC[AES256_GCM,data:n3ymHLkmRwt6C5azhzWUdOIEXB73NmcnALAf/TYm3W4=,iv:wGS1+67n5FYr41BHLNhmDkhZXuD5LHtp1bH5/hwojPw=,tag:Si865R+WbVQHX2/FdFIl9w==,type:str]
    BIFROST_API_KEY: ENC[AES256_GCM,data:gouYqhJJ0AbLmg5bQ2U8tGpLbKK6IAjYdJm56FjmlmKhjT0=,iv:7SQuViPIFpL8IobonzMshERQ9fEVqurTRvWRWr0RmmE=,tag:QcMVbkZqviotLFbWlGYOMw==,type:str]
    LLAMA_PC_API_KEY: ENC[AES256_GCM,data:yyz0SYpvVy06ikb63oIu/1ZIWJyi5vGuFg4GV/TJkYf+E86H/6IShNz+EcqbQU1/GpJDM9BkSkaUE2tGgESH0w==,iv:swujQWz2vcmcxifa//tCBqYdRqJzRjlRoLCzFSkInIw=,tag:3wWkNcuJFtnBc7B5mmPsOg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzT1o2YkNoSm9SV0dIbnpR
            R20zSmRBcVB5amVLQ0tiL0xYSlBhZEtKSEZzCmtnekxXN1BzeSsxeWdIaGMzK2JH
            LzBYeW52MUZJREFWKzdYUzF4N3pYbUEKLS0tIFc3SVdCRWFVL2pjdWJwRXhEL2w5
            K3gvZDVMRWRuR0tvcTNMdkU2VG1PSGsKN9yYROd2CcdZApNuZ3Orqhp42Z7Sngl1
            rcP+FIiSxdhbk+f+oNev+gEZTfJ8BgT4OnSb8POqv5hOgLHyZ+94nA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-29T20:36:12Z"
    mac: ENC[AES256_GCM,data:KXGyUbJ/K+30Q1/tR102SmRIvRiNC1BtUkmR3aKssm3kmjJeEOtSnEjxoeplDicIYqw+s9cKaeXRqon8lbyUcPnv9yr/UbdiaxBB/u2Ty66LeWLFqdIhlM8IMfyZf4UcGOMWwVhGcOpNFuofsVX0J/ZcKfvHXfz9oeHzIuOeoGA=,iv:ZaazyXFgtlOxb16vjLMZ0eprn9SDdVpukr6hYiFlXho=,tag:tb0jQh/n3Oah91eEQYjSRw==,type:str]
    version: 3.13.3
