# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: authelia
  namespace: security
type: Opaque
stringData:
  SECRET_POSTGRES_PASSWORD: ENC[AES256_GCM,data:aJ7u59A3fxSwtBorPAsX7OWWjV29k287Ey4n6yI9ajA6Dxfiupqp4RvQKwnUFM0T5t25lsdaMAkiR7fRiFPrvA==,iv:SJ6oqQC8N4lNKFB5Czi5SaxJlOQEUBS38EVA3C7eeDU=,tag:hlm/GSEBbdcgBn/3Owu0TA==,type:str]
  SECRET_SESSION_SECRET: ENC[AES256_GCM,data:OLOrAsFk5G+3+8qNX/NnX1rrb4Nxo7ZLldcH7xtgW3pCZ6ymNKIetfXcyeC/KlY5/SbKAO8mg1NhXjvWaFmw+w==,iv:ZN7uNCZdfJNpUw0ez0q6BLy1HpU0ZxUBRJpSc8zNr/4=,tag:UH5uwIr9+KaT2USQzZ8EoA==,type:str]
  SECRET_REDIS_PASSWORD: ENC[AES256_GCM,data:oTPRo8TcCbWZPQxcUG6SLF70A5WnpJo0Q/t126ibQYkNGGZ56ByVdWCWcOAO1YHgvyOLz7Kak9LATTLM4XBEMg==,iv:gwE1L5FKwuafntkGGE46WlK9xfVuJPuHpS4d0W1q23c=,tag:v3gnjmxvIYQxlkst9NCMvQ==,type:str]
  SECRET_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:0bMoILxTG7RAJEkaYTHFNBF7Iowiu1hWLekvieDs658RpLEmwS3fzvQYVfLmp+zIF0spuhHkqv4K88KukSXOOw==,iv:/lpyQdTG8tKXwEaoDOKj12SfmKLkWhTS2loCLAlKcm8=,tag:lz1i2Z+3MhgybpyO0RK/Jw==,type:str]
  SECRET_JWT_SECRET: ENC[AES256_GCM,data:nbkbmAbsL8AjjDTX8OIHuyxEd0UMeL9SkwWX+gB+PCvBKO45gMzCQbB6JLLPTbuKOcxsUMu3nw/mKHPuc1KmIA==,iv:AuMF6Mv/Sn3XLdHqTxdJJ0z27JJmVZzh5w6SoURDB7Q=,tag:rEkBtZT72aQ8dL18imkDdA==,type:str]
  SECRET_LDAP_PASSWORD: ENC[AES256_GCM,data:5IMDFFk1Cd79HNP+H8bxqCPkxBMfA6srpBWOiCL3nRg=,iv:tstPFyFeupk298hyQWuLW45qc6hPWmwF+k6QsTWBkw0=,tag:nx0DeMOlSpot0eEti51wmg==,type:str]
  SECRET_HMAC_SECRET: ENC[AES256_GCM,data:XxNSs2PtIaEsoxI7AWi2dVWBbwJVcQSNzWP9c3lwk1Nw73kAHDd37vD3NwSQf49aHZg9gWqOVGWSW2s13a4+kA==,iv:EpKYEeK4vku+9AIaTGfwOErhVo87IOA9E5a084g9kvM=,tag:OdnAD4O17sRzgggGNiJDpA==,type:str]
  SECRET_GRIST_KEY: ENC[AES256_GCM,data:qiMNJz7jTZAuSzcR8zXSGu2YdD9S3oxmBQtlRS7qJqg=,iv:5Qc7IhLFBZWvzd0qu1jIIcG5Xuuws3OrnkFbIaorvC4=,tag:S7QTmk3VD8pT5axBWU/FAw==,type:str]
  SECRET_METAMCP_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:rYqkOqkPtF8uSnjjez0dgVZ3L4yTJO1D8sDUMZHDxdCiJugCRDEQk7+DJWxxelh5,iv:9d0wShPg+tvghXDb8hx1OgMY1lDVlyFoau3SqJziW1I=,tag:usVDjfidcattsrCU30HcrQ==,type:str]
sops:
  age:
    - recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WmVMQTR2UlJmTXh6UE56
        N3VrNjM1VERURmo0S3hlMCtNRGhqcyt6a0Y0CnA0VG1sYTNnRHptdXdaKzhhRTll
        N0pZUm5MYTlpTm5FTGFXMzVtdXcxKzQKLS0tIHpWSzFlek9TbHJkcmVjUUlWY3p0
        cUJsdHFwRVhlUWlITzNxYjlQajcvQmcK5RLEyQVFq6Zb78huogCcRkQTGzQAZhRt
        F7g01jv0fWjMs4jqbOC66PfNRMgFZLCVG7bg7fi14Ighbz+1KpTadQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-30T16:13:07Z"
  mac: ENC[AES256_GCM,data:J/hofNhjVUt+q0a39Wqk+JfFTA0TUv/6+yGgzkl3/54fnglrlUcMfhVVONgqHLxLtk3DLX4nTvSOe8KFSooMyvuSiRZVusoYTiTXPKp0KweWynQ0l0BsQ9/u5rv7Zvoz781wv0Jmdg8Ryl7rwNmxs/p/teYrygEKl1TPY9UipmE=,iv:7+OJ3nAWC1PM6GuCPIn5f0IiE7pwbROSwj3FrGX7/Yk=,tag:Xaivy3GkwVaoxOcXDm4mxA==,type:str]
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
  version: 3.11.0
