# Plaintext on purpose. Encrypt this file with sops before applying to the cluster.
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}
  labels:
    app.kubernetes.io/name: ${APP}
type: Opaque
stringData:
  conduit.toml: ENC[AES256_GCM,data:y1ABANBvIt8Cdk5YtHJzNtxhxPojCr7DWzdOc1drmMTiJsGwrWJGEhrWbS6nj7F4Vh4TH8wBgNNbAKEaILIi7eGvh0g4zi4RTChBlV1wmjahIPqT+lo8/0TZaCLAPs9D8OH+MWgaHr1d3DXO/9REsrnegEx4NEAvtotK9IU3nTTkew7JdkaPMansfuswkgDSIvv8Q9JGAXIqlLTaXRp+Htrm4TsP1sGGghG1z+eb66OABx1hyYrVWtNwvhi0fPkb4LVJjtAzodCrtdoTJxraGKJm+xsJz+oWvhxjxfsUA7cNu5/dhHHZ+LK1dCTXxIxvTJNbRRHbmC0N8tWOpdK7wAp7zfhI6j8t1adk5n+PEVpfYWdGwix8vrBLhs4Oi8KQHESg4Mrk0kreYyNSTD1cu0KFj6RpPtIpapTOp2w4qXWSNo0T4UCPgbCaPBDTmmMVYampvnGI+f10t2fjqKXxCpyhOQyXGdWJnvnbidps6n4bl/5bSzr9sKLrwBuyLjBJQ6eKRoocVt5YfVTG3fZWeJGDThyjK5LLzRWxmCCFFkDjfQPLaWoa5txeUbuX+pycOAHrJAllEWhZBDMnll7wE8mAMbg9PmwlF6RBVNF8MNVifg770yv10C1fRKfnhNbR9AzvmZeyRcU/ImVCB4Tdq34M2QzmHqRQxu8k7IUTH3c9R7XySjbnxAsojukF18SUIGgtJQYTHhvvHclSHJWrIkCAj1C9pnWQPDUUZWs3NTKh5ZvK1+14vzPitYdK6uxzACz1QZJOgfG6wXjWoj+We4gAiUM1jnj05av34cAIBDJFf469THXAykj3X0OewfaZ0LAqWo/GfPPrk6LPUkXl0Ae+HBNyi0BIhbtAS0B2wU9PEp6kwwMSDqPM75IOHGAC3s5Z2nipjmxJpNVWaw498s41taCrQ7WDEcFOxmwv4Nlyx9iZJvNRcAOYO9x8QbdtvTpHaGYRyeNQRcrMxBzBue1cIcUkX58HXnWFWcgpPqGfG/3wtV6MxxApM3oyJ6ZstovDA0i0qH8B0bqI3r0+s43oaULpk6aNdQLBhJH9Y5TXf1Xjc/dNg0dmdl+Qm4Ic5ZuBGaTJKbH0yh7sHSxvd5W7UkRiwqpn3EQFC09enYAbWraIdo2g3pv1YO0zmyTEfMWQuFkQMR8V3wA1jbjcaV8aSGMkWZiIQvqRKNfmsHqubJPTx1erLnU6LNHcQjTb4inHwEWgmYO0rapm8Wk/UHXOniBeowSFiKNzCiqHay5KgWiHGnBQ42j5llvSucp+pRlkafrKEdf26E1e9uE9uh3wwG1OBfRIsDA7fbkJhD1j3ZEpoZKvxMhMk8BnOxrWeZHDWgTUrLqQmkF2WCawjB3vwLPvi/Wa2iRKNvWai4dXu7x2JkEX51Ts8z//,iv:GaTjkHCMpvWfRNCjv8fO6M9tIpc26aJ6iN/eWG28gGo=,tag:DPjfaUk8W5OeI5xtPaF12g==,type:str]
sops:
  age:
    - recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRmtKRHRpUjhpdEg2UDVI
        YklOcFN5R2xtR3dsTzEzUEZPd250R0RiSjFVCmZvTklRNXJJbWVka2lob095TTVs
        cStyWVN1WXZqbTl6QnpsclNTUDdWQkEKLS0tIHB1TkFYSE51THBFczdVVWJuUklj
        RVRrMkF2RVFUeHF6RkhINVdNNjNYVVUKEQGCBqzv/3mvN0KQXzMFV+NSzBiAX9y+
        sKAsNbnAD6ZxbE5qy7yKccxj1QC3J2lCCZMyJuUDzPoB/JQuQWzBSA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-12T09:49:13Z"
  mac: ENC[AES256_GCM,data:LP4nZqrJz8jvMyVyGR1MOLo4kJ5Gm0IY4Za8N3vC+wGGc3vToL8tvrDr5HfICT2DBgSAaS3bMrmCa5WNk5D7zPiq+njPvtb4wL9xGVByM3iXnsxRDgBYSoSFHv2nOqfNxvwRtBZw4RDQyfUiiMcNkeMoBrlBE4E29Kt1VseTF+4=,iv:DqmClI1RAkz316njjbEzXmJUAPAfZ6ci1s3b4O2+TW0=,tag:RPIu1w8pkK4VUnRHFJkbOQ==,type:str]
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
  version: 3.11.0
