# Plaintext on purpose. Encrypt this file with sops before applying to the cluster.
apiVersion: v1
kind: Secret
metadata:
    name: ${APP}
    labels:
        app.kubernetes.io/name: ${APP}
type: Opaque
stringData:
    conduit.toml: ENC[AES256_GCM,data:u0TdiirnxA02ad8QR8dj/ZoOt9aipStB8n559OGVRBHA12UbOyv+PCpj6AiQGkcXnS/t6biJlj/Grd2Ikoj3680IQAEqEQsY2ps3/dgLxujHY7OcA2va+QOAIxe7khuZ6TRWYjct0rmAt9b93ihTXQByxaXOrMNA60WKN+LLn1XzvLBbs9QjphN1+hvplWzxFjte7pNz0u3MV7bt2dJqha2O6+j3Nwb75E17nBJ38Nvt23OOxAPZTae+bPW2oJijggYvs3B4EF7Rgv6RZxsirXrGutvuNwRAAIWqCWfuvycNCiNJSrsR84UdZsUwxMHD8kBeQu/jY2SvdmQeX+/YFbuOqV0uQN64wmoCbZgPUEVr4dOW3L6Pl/y4Xs5j/tBKb68aUb3HyVglanD2Xyk8LGrs+/+17DUWdqdZYPyT64mwzzCIL7Mhskiwn1l0L2n7fND/p7dWUQyjdpMfXgrHHHF2hXPXteHPwKESuYohKSkyVkCpwlUNPbF7xUMdEfdyiu1bDfcYewsu2wt8LtpJrSP2/aka/IYNREkoYRaLU09P6uywydkws2qaxVL0D4QAoVI+0nPoOCpUVi5c2c7AKJmjtE2SDCP+IjH7NT855bEGYydF9hTmAW5AU0uMFneZsznquk8Uv+Pd8tK8aGhpJxF7wp+ewrAp4SuKwY6YHleFrpvze0d1UH8p9QF+HIrBNq3huh7kefaI0la8+NAf5S+ydhqq9MajkRJWDos084avwVRkrbgOQeDuHKc7Klu3x2m76zytrHYOb1Y+6VlRZVfQp+j842R3mm+jCQvSpE8vJrJAOP06n0ycJ/DTOBSlBBM07JsQ3nytUvnZIhhaii4KdHUr+TQNlM2qBZdTrGOxu+OvFiqHH8KTnAnIiIS2tXHIQuiofd2gV9CihvNkkNLkVQtwPYc9cZf1kUrf0cfKyD2Uf0Fy6Gq2INLY4DwF5wmQx46jAgjPhvLRuFdS0NjF3S2N2uAQFpW6GkbuJ1T081JKBaF7jFg5SkYnAEEXovWAb5jEfFSTdmgI2jIxBuV/I76w5nRv6kz26LwCQghtuK7iReRGChhjl2TUIe/2PMh7/7cbWqU91XfZpuOs41I0YC5s8aXzsCqR8g==,iv:R0Zl4em9P9674QO9bNG+tWTDc75UCQn539tIfC0AGKU=,tag:52xilzfv3hHUoCvrr2t2Iw==,type:str]
sops:
    age:
        - recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweTZ1SWFFL0VYR1dzS3gx
            M2ZqcHE2K0crWE5ZZjZFbllYYjhPRUE1YWpZCm1Jd08wa2VxeWhoTUhNRlM5T3g5
            TUxLWGNjV2hqYXoyV3RGYkNSUE9IalUKLS0tIEgwOUJmc2tZUi9hY1BqYmM4bmZF
            eWo4RkszbVJTczByZGJoM2ErUGJiNkkK0moqjEOA6HaadvY9JUY8RCCGK+1Xge8n
            lLBhoxJ+g55QVpuzARxQsXy9kTLYiu8C8VJ2acKIG7RQ2YAnMaspFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T09:12:30Z"
    mac: ENC[AES256_GCM,data:2sQoU1saAht51+HH+WW1I01WnI+NgKP0AJ/eWM48dgaX+S8bhL0jOpcedGZrK6MleO9sC83Go93qMd3beAbJCUSdwvbVOyDeFWCaQKlJftS0qSB6IpASN8vgaopixQpQBF6/t5+WawqUUz+Bw14QwO9wNRFsM9G5PSaELQGgWqQ=,iv:rJVhRaciCiX5dKCw0cEiEP48+5nqcORW/OYLRtavQsM=,tag:Z+iqa0TuyFMSYY9ZJAy01A==,type:str]
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
