apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-secret
type: Opaque
stringData:
    SECRET_ENCRYPTION_KEY: ENC[AES256_GCM,data:WBI04UUMqJtc+xKeoV7kql0n/EJlFG/HxNgF3puWUKBdFIlb0rj44ZX4PBL7gWXQ8Wy7YIL0TYVZ8VdhxIC/CA==,iv:HxeSp8gaTtH56BgnmaRjcObT8J/Fmpa6GXBIJbnJKHc=,tag:2mesYO8SQ9/oiYuOG/Rzaw==,type:str]
    AUTH_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:0MWtD4MnbXv0RB8QzkImeDyrTMY5vsIDeqH4iXQYtvI=,iv:WQuLV1vfsYZYf5Vw5nB97jU7DA5Z4Poy9uHY+D8WZFE=,tag:zBJAYY7AZ8iiMB9yiICXuQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Z2F3ZDZVd0tDbVlUZEJK
            WFJGWG1sZ2liV3BZSEZOcUVvYjFycXdPcEdZCnZ4SG5QNHJJNTZoMzN1dU1XRWFn
            OTZacHFLOCtzbUZWL0VoNyt0SG5JUXMKLS0tIGdzMkFuYzhlVnBDMGxiQks2YU1C
            RDNZV1gyNUVETDN0bXdpTTE0UngyQVkKqwHCfd9B6VE14W+oCa7X7az8+H4Jptz6
            8mpKH8mFFSwu80OCLCGJcEjGHJjuxhLmNfhTkENdvpqS2Xwqci6UaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-18T21:22:42Z"
    mac: ENC[AES256_GCM,data:Ygjp38+6rGeMvJBC7mGrZHU7/rgcN9WdW4kX8x4dHnb1z6KdgTYyMlMDMhyZwtGmmWNkUUg/CLL3i+zlapoe+j/OpNRkxpFqwtPwbl9hoiquf3T8IsoNp0mzNG5+7RIx8LryCJw2AEPYi73CQHN+LikpkzcxdWhMiuqrwDUEpto=,iv:bjb8yy2g1Z0vqzimGR+ntq3sY1O3M7fUKktA4N/yb3A=,tag:JixKV67GlvcbhhFtmdKg6A==,type:str]
    version: 3.13.3
