---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ess-matrixrtc-cors
  namespace: messaging
spec:
  headers:
    accessControlAllowCredentials: true
    accessControlAllowHeaders:
      - Accept
      - Authorization
      - Content-Type
      - Content-Length
      - Accept-Encoding
      - X-CSRF-Token
    accessControlAllowMethods:
      - GET
      - POST
      - OPTIONS
    accessControlAllowOriginList:
      - https://matrix.${SECRET_PUBLIC_DOMAIN}
    accessControlAllowOriginListRegex:
      - "^https://[^.]+\\.matrix\\.${SECRET_PUBLIC_DOMAIN}$"
