#!/bin/sh

ENABLED=yes
PROCS=cs-firewall-bouncer
ARGS="-c /opt/etc/crowdsec/crowdsec-firewall-bouncer.yaml"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
