---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-5.1.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 5.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      gatus:
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          app:
            image:
              repository: ghcr.io/twin/gatus
              tag: v5.37.0
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                memory: 256Mi
    service:
      app:
        controller: gatus
        ports:
          http:
            primary: true
            port: 8080
    route:
      app:
        enabled: true
        kind: HTTPRoute
        parentRefs:
          - name: public
            sectionName: websecure-public
            namespace: networking
        hostnames:
          - gatus.${SECRET_PUBLIC_DOMAIN}
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - identifier: app
                port: 8080
            filters:
              - type: ExtensionRef
                extensionRef:
                  group: traefik.io
                  kind: Middleware
                  name: oidc-authenticated
        annotations:
          external-dns.kubernetes.io/enabled: 'true'
          external-dns.kubernetes.io/target: ${INGRESS_DEFAULT}
          external-dns.kubernetes.io/cloudflare-proxied: ${quote}${INGRESS_DEFAULT_CF_PROXY}${quote}
          gethomepage.dev/enabled: 'true'
          gethomepage.dev/group: Maintenance
          gethomepage.dev/icon: /icons/gatus/${HOMEPAGE_ICONS_COLOR}
          gethomepage.dev/name: Gatus
          gethomepage.dev/weight: '-100'
          gethomepage.dev/widget.type: gatus
          gethomepage.dev/widget.url: http://gatus.monitoring:8080
    persistence:
      config:
        enabled: true
        type: secret
        name: gatus-config
        defaultMode: 0555
        globalMounts:
          - path: /config/config.yaml
            subPath: config.yaml
            readOnly: true
