---
apiVersion: v1
kind: Service
metadata:
  name: ext-svc-parents
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
    traefik.ingress.kubernetes.io/service.serverstransport: default_parents-insecure@kubernetescrd
spec:
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ext-svc-parents
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.100.102
    ports:
      - port: 443
        name: https
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: parents-passthrough
  namespace: default
spec:
  parentRefs:
    - name: public
      namespace: networking
      sectionName: websecure
  hostnames:
    - "${SECRET_PARENTS_DOMAIN}"
    - "*.${SECRET_PARENTS_DOMAIN}"
  rules:
    - backendRefs:
        - name: ext-svc-parents
          port: 443
