---
apiVersion: v1
kind: Service
metadata:
  name: ext-svc-parents
  namespace: default
spec:
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ext-svc-parents
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.100.102
    ports:
      - port: 443
        name: https
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: parents-passthrough
  namespace: default
spec:
  gatewayClassName: traefik-public
  listeners:
    - name: parents
      hostname: "${SECRET_PARENTS_DOMAIN}"
      protocol: TLS
      port: 8443
      tls:
        mode: Passthrough
    - name: parents-wildcard
      hostname: "*.${SECRET_PARENTS_DOMAIN}"
      protocol: TLS
      port: 8443
      tls:
        mode: Passthrough
---
apiVersion: gateway.networking.k8s.io/v1
kind: TLSRoute
metadata:
  name: parents-passthrough
  namespace: default
spec:
  parentRefs:
    - name: parents-passthrough
      sectionName: parents
    - name: parents-passthrough
      sectionName: parents-wildcard
  hostnames:
    - "${SECRET_PARENTS_DOMAIN}"
    - "*.${SECRET_PARENTS_DOMAIN}"
  rules:
    - backendRefs:
        - name: ext-svc-parents
          port: 443
