# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: plik
  namespace: default
stringData:
  PLIK_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:5grQT+jWrCwBcA==,iv:hLF374Z5PdB/P5H2rsF30MtoQ9ionrOIlNv3BQ47cW4=,tag:9zoaRSspvW+vTwy3ffKRxA==,type:str]
  PLIK_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:eeShGCI5OOIZ6JkB6zsQzSOQYthDIJ9LnH9HYfvavIdsFonI1Z0DTQ==,iv:456ciX6Jz8cn9nSo8oVa8LaW/xbYVwcnQI5K3VeN+aU=,tag:ECbIuElzVm4NElNkQx5EBg==,type:str]
sops:
  age:
    - recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQ01kRWxoaHVsODArUDFX
        L1ZMcllIaS9Rbkl6elNYbGxqOEdHWWE4dHdZCm1Pd2paUWl3ZHF1dU54cjYrZERG
        YlRIUkI3ZkJ3dGR3WHhoNlZjaEwwS3MKLS0tIDFCRm4vV2xmSkJ1QUViZzNyNnFK
        KzliQVlGQXUvbUFMZ1N4clhTNmhJZlUKPjiQ4NMYmv9CG7An5lUKqMVDXJQzlRkP
        KruPETWF+bRuL5q/Atg0KA9nZ8Dwq/N+ZfSss7wi6DLxOzO2zCEJ8Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-31T09:51:46Z"
  mac: ENC[AES256_GCM,data:92S8zMxv55qJ5FxjMGZg5Kz2xdYYLDBfeSsFtcZMbsVK2aytR0FqOXDY5j2/xBB5v0+6qQRNmeyeLG6oQvtmcur/u7IODB1vnD2uTDmsUfYFcsFLmMQtUjpBnKJdnzFKzBMefIgdDFjWPRZGTC4sSObYWtmqViliyvka79N0VBQ=,iv:pn5Ec05jpaubRLxsOyGAMyq2lP1uTqeh6Sn6W9zt6P8=,tag:23rwNNHC7KKPgscAfVpppQ==,type:str]
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
  version: 3.11.0
