# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: plik
    namespace: default
stringData:
    PLIK_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:K/jU7SURWsJpUw==,iv:ZXjIrBlBqueoQt0rFW/sra7ljFdQwoNN5HcCch9Ayn0=,tag:MDx4x/2n7V2SKC/rAT0UAA==,type:str]
    PLIK_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:gTxIAeZba4SZtoqk47HrYKsBn1trzLA7ZbWnNUDI1+H36osG+orvFA==,iv:wZNCZL8YIkQ0x2MutWEnjTBIfh6D8JUPSMc0h2nBzTY=,tag:N1Uznpa2QWvXi8bY/oCVJQ==,type:str]
    PLIKD_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:dIHC/Kz5Q8BvNSBzuwbhG8u0MBHzGzfTtt3KU2/vu/c=,iv:hjLk06bc9od1SLa9JiX9GnlysmTnk7rcerKrE/fnAoQ=,tag:yEXSFpoyVf8wBY7t3tGcAg==,type:str]
    PLIKD_DATA_BACKEND_CONFIG: ENC[AES256_GCM,data:9QfQ0C/2t/dyErLhOChbOP8Z/dXr5PxA/EF8szn0hRbxpFV4wSOwFpkvegGYKpw8R8ECP6ZspG6sO18nsdH3evKNgKxHzmR4wFxVyqBf8yvBPPVYL7P9kGwBVE1guTRlFqKCBoK10ReWFl5VN5ZiHn9TCQwPi6+oV9Hynu2HWU8glfy820q9pnTb2QPVGTSkO7WZdJYPhBxEHgvAlyFmlVxuLsenHPeAE6TaIcUHTjJfNxDQgOkTFLCWm1wwnOKm/GBf7Ff9gvqsURUckL5L9c1OypI1ToS5Z2Kr5ibXUv38Ys3oIRadxOLxLVJB87bbEXqOb57wPEJ/X7qFL90JbICKG/4/BOGA1LSSoM8S0VFbZ1M87kmrbjJAIrqcyvnPC0FpVuZjjKDx25ZUIfVKUhaMhNPr3OA=,iv:Dhg43nAtT1YJ6/0j9B7CLL2Z/F73Pijj29GOJQgiztI=,tag:96UOGuFyzCwsKqw4vHuVLA==,type:str]
    PLIKD_METADATA_BACKEND_CONFIG: ENC[AES256_GCM,data:Yk3efZI8DxoAryUWWaLR7ZtsfCpi6JpkS6cWWr+FqIv88WbaSYym+GYWE5xFkIzYbiXLi9BZVuuzhJpiwTkIKSdTpX0t0nQoFWI3o1HchcmEgxV72Bw5Ie677VSKEnEplmw45+bdvmXQ4ygysDQBtqzwtVNmLJ9p5W3KhBI1Ip5NNaxZUW7bd4ijIJrxjujunNM6ESIIE3vKNUWAaxRxZRSz0mExQbJYZVWCVw/HHvuIIT1FCtKywgMtbtXFn4+7sEGSJvxAnSqQtMJgwDCQ5XIXQzVw2tyxB4zAnkGNN5s=,iv:Dk1e3Nj7YhR+d/DaKV1YUmamKAKsvgoVxkAhvm/4oyY=,tag:P1oGCI883FWICCbmM/ZWCg==,type:str]
sops:
    age:
        - recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKV2Q4ZEpiRnk0Qlc5SU5p
            SjRrWWdSNmtUZDNFYnREU3R0STc3VjhCZWtjCjNsdkhXK2VxRXJlT0ZLTlRaK0I5
            UFZlMDdxM0I3b0pzWWJmczM4cFlUYUEKLS0tIFBPUnhLdlJyVkwremVLc1NyOVRh
            a1pkWE05K01Lb1FsY3RpN1NtY1A2aWMKMK5BY25yP6FdA7g5KpWBXOTnVn05qcW/
            sdThLc2NgVvdRl7+pZN/izjutNWds+pr6AnuGPsRcryDvC+4laICEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T10:06:03Z"
    mac: ENC[AES256_GCM,data:7/e1Yj50nFAxioBiMzs8dvN0J3hCrugTRbfkKJqqNZikQBdXqhukPyD4g58WC5kI9BPpMUgqaUwAMFX8/vZNJaDE5PsPTH0HwjdCMkgV4cJDEF6jUHr7YZrq9XrmXQpOmGq6iWoveQOLGo7a2M/x+MVdt+5d2HQetI+9LbFWarw=,iv:60HD26aDueHsqEHwKROvxEIbxmQLhMzMCDH1xPOg+9Q=,tag:0kS+x20O0emBvqP3eAaJaQ==,type:str]
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
