apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-secret
type: Opaque
stringData:
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:VNf9s7Dlh/YtOSLnWkobmIohcAa1kjjPt8Ofhu+TtXE=,iv:ZdqaWElKlszXPY21VGRpp96Anv+rmAblR1gkTz+Vkow=,tag:czPq+eOWBi5ZucDP7mCX9Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Z2F3ZDZVd0tDbVlUZEJK
            WFJGWG1sZ2liV3BZSEZOcUVvYjFycXdPcEdZCnZ4SG5QNHJJNTZoMzN1dU1XRWFn
            OTZacHFLOCtzbUZWL0VoNyt0SG5JUXMKLS0tIGdzMkFuYzhlVnBDMGxiQks2YU1C
            RDNZV1gyNUVETDN0bXdpTTE0UngyQVkKqwHCfd9B6VE14W+oCa7X7az8+H4Jptz6
            8mpKH8mFFSwu80OCLCGJcEjGHJjuxhLmNfhTkENdvpqS2Xwqci6UaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vxxfmwathgflpvu4wgqpugtjj6tg9f3f3jyp42vfqv0her6hm3js9ny8f4
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-27T18:14:47Z"
    mac: ENC[AES256_GCM,data:LvgOvDO+o+k0/dqU90kz/3YkX5Ftv9MjStdQ1mD1YHpZMVMxh1Y4KpHmqR/BpHHrXsUcS/GbxYooUwM9X1m64Z6cFlcND1suiw3f3pjBz6DZwJqFx1nbQwHBZKWOH/IRXXQN5CphfmtXojOy2PFcAEl9sU837Czjs/WkfeGNNbw=,iv:CFgMqn9kqHB9Ux5ZWPTZ/pKd7xLLrTK+6sZRg2z6P/w=,tag:bp5XcwfVYoSmo7Y6a4OciQ==,type:str]
    version: 3.13.3
