---
- name: Prepare / Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - wireguard
    state: latest
    update_cache: true

- name: Prepare / Create apt keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Prepare / Add Docker GPG keyring
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Prepare / Add Docker Repository
  apt_repository:
    repo: "deb [arch={{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Prepare / Remove distro Docker Compose packages
  apt:
    pkg:
      - docker-compose
      - docker-compose-v2
    state: absent

- name: Prepare / Install Docker
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - python3-docker
    state: latest
    update_cache: true

- name: Prepare / Create docker networks
  community.docker.docker_network:
    name: "{{ item.name }}"
    state: present
  when: docker_create_networks is defined
  loop: "{{ docker_create_networks }}"
