---
- name: Traefik / Create config directory
  file:
    path: "/opt/traefik"
    state: directory
    mode: '0755'

- name: Traefik / Determine port openings with IPv6
  set_fact:
    traefik_ipv6_ports: |
      - "{{ '[' + external_ipv6 + ']:80:80' }}"
      - "{{ '[' + external_ipv6 + ']:443:443' }}"
  when: external_ipv6 is defined

- name: Traefik / Set default port openings
  set_fact:
    traefik_ipv6_ports: ""
  when: external_ipv6 is undefined

- name: Traefik / Create docker-compose.yml file
  template:
    src: traefik-docker-compose.yml.j2
    dest: "/opt/traefik/docker-compose.yml"
    owner: root
    group: root
    mode: '0644'

- name: Traefik / Create config file
  template:
    src: traefik-config.yml.j2
    dest: "/opt/traefik/traefik-config.yml"
    owner: root
    group: root
    mode: '0644'

- name: Traefik / Deploy with docker-compose
  community.docker.docker_compose_v2:
    project_src: "/opt/traefik"
    state: present

- name: Traefik / Restart with docker-compose
  community.docker.docker_compose_v2:
    project_src: "/opt/traefik"
    state: restarted

- name: Traefik / Show DoH proxy endpoints
  ansible.builtin.debug:
    msg: |
      DoH proxy endpoints:
      | Name | Original URL | Proxied URL |
      | --- | --- | --- |
      {% for upstream in traefik_doh_proxy_upstreams %}
      | {{ upstream.name }} | {{ upstream.url }}/dns-query | {% for hostname in [traefik_base_domain] + dnsproxy_alternative_hostnames %}https://{{ hostname }}{{ traefik_doh_proxy_path_prefix }}/{{ upstream.name }}{% if not loop.last %}<br>{% endif %}{% endfor %} |
      {% endfor %}
  when: traefik_doh_proxy_enabled | bool
