---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crowdsec-web-ui-config
  namespace: security
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
