---
name: Build OpenQuester Images

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "containers/openquester-*/**"
      - ".github/workflows/build-openquester-images.yaml"

env:
  OPENQUESTER_REF: f083d460f77adf3b5ec7a260cce124342c9844a1

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v7
        with:
          context: containers/openquester-web
          push: true
          build-args: |
            OPENQUESTER_REF=${{ env.OPENQUESTER_REF }}
            API_URL=/
            CLIENT_APP_URL=/
          tags: ghcr.io/${{ github.repository_owner }}/openquester-web:${{ env.OPENQUESTER_REF }}
          labels: org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - uses: docker/build-push-action@v7
        with:
          context: containers/openquester-server
          push: true
          build-args: OPENQUESTER_REF=${{ env.OPENQUESTER_REF }}
          tags: ghcr.io/${{ github.repository_owner }}/openquester-server:${{ env.OPENQUESTER_REF }}
          labels: org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
